CREATE TABLE IF NOT EXISTS public.questions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    form_id UUID NOT NULL REFERENCES public.forms(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    placeholder TEXT,
    is_required BOOLEAN DEFAULT false,
    question_type TEXT NOT NULL,
    position INTEGER,
    options JSONB,
    validation_rules JSONB,
    conditional_logic JSONB,
    default_value TEXT,
    max_character_count INTEGER,
    show_character_count BOOLEAN DEFAULT false,
    rating_scale INTEGER,
    rating_type TEXT,
    allowed_file_types TEXT[],
    max_file_size INTEGER,
    max_files INTEGER
); 