-- =========================
-- SEED: CURRENCIES (from https://developers.google.com/public-data/docs/canonical/currencies_csv)
-- =========================
INSERT INTO public.currencies (code, name, symbol)
VALUES
  ('AED', 'UAE Dirham', NULL),
  ('AFN', 'Afghani', '؋'),
  ('ALL', 'Lek', 'Lek'),
  ('AMD', 'Armenian Dram', NULL),
  ('ANG', 'Netherlands Antillian Guilder', 'ƒ'),
  ('AOA', 'Kwanza', NULL),
  ('ARS', 'Argentine Peso', '$'),
  ('AUD', 'Australian Dollar', '$'),
  ('AWG', 'Aruban Guilder', 'ƒ'),
  ('AZN', 'Azerbaijanian Manat', 'ман'),
  ('BAM', 'Convertible Marks', 'KM'),
  ('BBD', 'Barbados Dollar', '$'),
  ('BDT', 'Taka', NULL),
  ('BGN', 'Bulgarian Lev', 'лв'),
  ('BHD', 'Bahraini Dinar', NULL),
  ('BIF', 'Burundi Franc', NULL),
  ('BMD', 'Bermudian Dollar (customarily known as Bermuda Dollar)', '$'),
  ('BND', 'Brunei Dollar', '$'),
  ('BOB', 'Boliviano', '$b'),
  ('BOV', 'Mvdol', NULL),
  ('BRL', 'Brazilian Real', 'R$'),
  ('BSD', 'Bahamian Dollar', '$'),
  ('BTN', 'Ngultrum', NULL),
  ('BWP', 'Pula', 'P'),
  ('BYR', 'Belarussian Ruble', 'p.'),
  ('BZD', 'Belize Dollar', 'BZ$'),
  ('CAD', 'Canadian Dollar', '$'),
  ('CDF', 'Congolese Franc', NULL),
  ('CHF', 'Swiss Franc', 'CHF'),
  ('CLP', 'Chilean Peso', '$'),
  ('CLF', 'Unidades de fomento', '$'),
  ('CNY', 'Yuan Renminbi', '¥'),
  ('COP', 'Colombian Peso', '$'),
  ('COU', 'Unidad de Valor Real', NULL),
  ('CRC', 'Costa Rican Colon', '₡'),
  ('CUC', 'Peso Convertible', '₱'),
  ('CUP', 'Cuban Peso', '₱'),
  ('CVE', 'Cape Verde Escudo', NULL),
  ('CZK', 'Czech Koruna', 'Kč'),
  ('DJF', 'Djibouti Franc', NULL),
  ('DKK', 'Danish Krone', 'kr'),
  ('DOP', 'Dominican Peso', 'RD$'),
  ('DZD', 'Algerian Dinar', NULL),
  ('EEK', 'Kroon', NULL),
  ('EGP', 'Egyptian Pound', '£'),
  ('ERN', 'Nakfa', NULL),
  ('ETB', 'Ethiopian Birr', NULL),
  ('EUR', 'Euro', '€'),
  ('FJD', 'Fiji Dollar', '$'),
  ('FKP', 'Falkland Islands Pound', '£'),
  ('GBP', 'Pound Sterling', '£'),
  ('GEL', 'Lari', NULL),
  ('GHS', 'Cedi', NULL),
  ('GIP', 'Gibraltar Pound', '£'),
  ('GMD', 'Dalasi', NULL),
  ('GNF', 'Guinea Franc', NULL),
  ('GTQ', 'Quetzal', 'Q'),
  ('GYD', 'Guyana Dollar', '$'),
  ('HKD', 'Hong Kong Dollar', '$'),
  ('HNL', 'Lempira', 'L'),
  ('HRK', 'Croatian Kuna', 'kn'),
  ('HTG', 'Gourde', NULL),
  ('HUF', 'Forint', 'Ft'),
  ('IDR', 'Rupiah', 'Rp'),
  ('ILS', 'New Israeli Sheqel', '₪'),
  ('INR', 'Indian Rupee', NULL),
  ('IQD', 'Iraqi Dinar', NULL),
  ('IRR', 'Iranian Rial', '﷼'),
  ('ISK', 'Iceland Krona', 'kr'),
  ('JMD', 'Jamaican Dollar', 'J$'),
  ('JOD', 'Jordanian Dinar', NULL),
  ('JPY', 'Yen', '¥'),
  ('KES', 'Kenyan Shilling', NULL),
  ('KGS', 'Som', 'лв'),
  ('KHR', 'Riel', '៛'),
  ('KMF', 'Comoro Franc', NULL),
  ('KPW', 'North Korean Won', '₩'),
  ('KRW', 'Won', '₩'),
  ('KWD', 'Kuwaiti Dinar', NULL),
  ('KYD', 'Cayman Islands Dollar', '$'),
  ('KZT', 'Tenge', 'лв'),
  ('LAK', 'Kip', '₭'),
  ('LBP', 'Lebanese Pound', '£'),
  ('LKR', 'Sri Lanka Rupee', '₨'),
  ('LRD', 'Liberian Dollar', '$'),
  ('LSL', 'Loti', NULL),
  ('LTL', 'Lithuanian Litas', 'Lt'),
  ('LVL', 'Latvian Lats', 'Ls'),
  ('LYD', 'Libyan Dinar', NULL),
  ('MAD', 'Moroccan Dirham', NULL),
  ('MDL', 'Moldovan Leu', NULL),
  ('MGA', 'Malagasy Ariary', NULL),
  ('MKD', 'Denar', 'ден'),
  ('MMK', 'Kyat', NULL),
  ('MNT', 'Tugrik', '₮'),
  ('MOP', 'Pataca', NULL),
  ('MRO', 'Ouguiya', NULL),
  ('MUR', 'Mauritius Rupee', '₨'),
  ('MVR', 'Rufiyaa', NULL),
  ('MWK', 'Kwacha', NULL),
  ('MXN', 'Mexican Peso', '$'),
  ('MXV', 'Mexican Unidad de Inversion (UDI)', NULL),
  ('MYR', 'Malaysian Ringgit', 'RM'),
  ('MZN', 'Metical', 'MT'),
  ('NAD', 'Namibia Dollar', NULL),
  ('NGN', 'Naira', '₦'),
  ('NIO', 'Cordoba Oro', 'C$'),
  ('NOK', 'Norwegian Krone', 'kr'),
  ('NPR', 'Nepalese Rupee', '₨'),
  ('NZD', 'New Zealand Dollar', '$'),
  ('OMR', 'Rial Omani', '﷼'),
  ('PAB', 'Balboa', 'B/.'),
  ('PEN', 'Nuevo Sol', 'S/.'),
  ('PGK', 'Kina', NULL),
  ('PHP', 'Philippine Peso', 'Php'),
  ('PKR', 'Pakistan Rupee', '₨'),
  ('PLN', 'Zloty', 'zł'),
  ('PYG', 'Guarani', 'Gs'),
  ('QAR', 'Qatari Rial', '﷼'),
  ('RON', 'New Leu', 'lei'),
  ('RSD', 'Serbian Dinar', 'Дин.'),
  ('RUB', 'Russian Ruble', 'руб'),
  ('RWF', 'Rwanda Franc', NULL),
  ('SAR', 'Saudi Riyal', '﷼'),
  ('SBD', 'Solomon Islands Dollar', '$'),
  ('SCR', 'Seychelles Rupee', '₨'),
  ('SDG', 'Sudanese Pound', NULL),
  ('SEK', 'Swedish Krona', 'kr'),
  ('SGD', 'Singapore Dollar', '$'),
  ('SHP', 'Saint Helena Pound', '£'),
  ('SLL', 'Leone', NULL),
  ('SOS', 'Somali Shilling', 'S'),
  ('SRD', 'Surinam Dollar', '$'),
  ('STD', 'Dobra', NULL),
  ('SYP', 'Syrian Pound', '£'),
  ('SZL', 'Lilangeni', NULL),
  ('THB', 'Baht', '฿'),
  ('TJS', 'Somoni', NULL),
  ('TMT', 'Manat', NULL),
  ('TND', 'Tunisian Dinar', NULL),
  ('TOP', 'Pa''anga', NULL),
  ('TRY', 'Turkish Lira', 'TL'),
  ('TTD', 'Trinidad and Tobago Dollar', 'TT$'),
  ('TWD', 'New Taiwan Dollar', 'NT$'),
  ('TZS', 'Tanzanian Shilling', NULL),
  ('UAH', 'Hryvnia', '₴'),
  ('UGX', 'Uganda Shilling', NULL),
  ('USD', 'US Dollar', '$'),
  ('UYU', 'Peso Uruguayo', '$U'),
  ('UZS', 'Uzbekistan Sum', 'лв'),
  ('VEF', 'Bolivar Fuerte', 'Bs'),
  ('VND', 'Dong', '₫'),
  ('VUV', 'Vatu', NULL),
  ('WST', 'Tala', NULL),
  ('XAF', 'CFA Franc BEAC', NULL),
  ('XAG', 'Silver', NULL),
  ('XAU', 'Gold', NULL),
  ('XBA', 'Bond Markets Units European Composite Unit (EURCO)', NULL),
  ('XBB', 'European Monetary Unit (E.M.U.-6)', NULL),
  ('XBC', 'European Unit of Account 9(E.U.A.-9)', NULL),
  ('XBD', 'European Unit of Account 17(E.U.A.-17)', NULL),
  ('XCD', 'East Caribbean Dollar', '$'),
  ('XDR', 'SDR', NULL),
  ('XFU', 'UIC-Franc', NULL),
  ('XOF', 'CFA Franc BCEAO', NULL),
  ('XPD', 'Palladium', NULL),
  ('XPF', 'CFP Franc', NULL),
  ('XPT', 'Platinum', NULL),
  ('XTS', 'Codes specifically reserved for testing purposes', NULL),
  ('YER', 'Yemeni Rial', '﷼'),
  ('ZAR', 'Rand', 'R'),
  ('ZMK', 'Zambian Kwacha', NULL),
  ('ZWL', 'Zimbabwe Dollar', NULL)
ON CONFLICT (code) DO NOTHING;

-- =========================
-- SEED: LANGUAGES (ISO 639-1)
-- =========================
INSERT INTO public.languages (code, name)
VALUES
  ('aa', 'Afar'),
  ('ab', 'Abkhazian'),
  ('ae', 'Avestan'),
  ('af', 'Afrikaans'),
  ('ak', 'Akan'),
  ('am', 'Amharic'),
  ('an', 'Aragonese'),
  ('ar', 'Arabic'),
  ('as', 'Assamese'),
  ('av', 'Avaric'),
  ('ay', 'Aymara'),
  ('az', 'Azerbaijani'),
  ('ba', 'Bashkir'),
  ('be', 'Belarusian'),
  ('bg', 'Bulgarian'),
  ('bi', 'Bislama'),
  ('bm', 'Bambara'),
  ('bn', 'Bengali'),
  ('bo', 'Tibetan'),
  ('br', 'Breton'),
  ('bs', 'Bosnian'),
  ('ca', 'Catalan; Valencian'),
  ('ce', 'Chechen'),
  ('ch', 'Chamorro'),
  ('co', 'Corsican'),
  ('cr', 'Cree'),
  ('cs', 'Czech'),
  ('cu', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'),
  ('cv', 'Chuvash'),
  ('cy', 'Welsh'),
  ('da', 'Danish'),
  ('de', 'German'),
  ('dv', 'Divehi; Dhivehi; Maldivian'),
  ('dz', 'Dzongkha'),
  ('ee', 'Ewe'),
  ('el', 'Greek, Modern (1453-)'),
  ('en', 'English'),
  ('eo', 'Esperanto'),
  ('es', 'Spanish; Castilian'),
  ('et', 'Estonian'),
  ('eu', 'Basque'),
  ('fa', 'Persian'),
  ('ff', 'Fulah'),
  ('fi', 'Finnish'),
  ('fj', 'Fijian'),
  ('fo', 'Faroese'),
  ('fr', 'French'),
  ('fy', 'Western Frisian'),
  ('ga', 'Irish'),
  ('gd', 'Gaelic; Scottish Gaelic'),
  ('gl', 'Galician'),
  ('gn', 'Guarani'),
  ('gu', 'Gujarati'),
  ('gv', 'Manx'),
  ('ha', 'Hausa'),
  ('he', 'Hebrew'),
  ('hi', 'Hindi'),
  ('ho', 'Hiri Motu'),
  ('hr', 'Croatian'),
  ('ht', 'Haitian; Haitian Creole'),
  ('hu', 'Hungarian'),
  ('hy', 'Armenian'),
  ('hz', 'Herero'),
  ('ia', 'Interlingua (International Auxiliary Language Association)'),
  ('id', 'Indonesian'),
  ('ie', 'Interlingue; Occidental'),
  ('ig', 'Igbo'),
  ('ii', 'Sichuan Yi; Nuosu'),
  ('ik', 'Inupiaq'),
  ('io', 'Ido'),
  ('is', 'Icelandic'),
  ('it', 'Italian'),
  ('iu', 'Inuktitut'),
  ('ja', 'Japanese'),
  ('jv', 'Javanese'),
  ('ka', 'Georgian'),
  ('kg', 'Kongo'),
  ('ki', 'Kikuyu; Gikuyu'),
  ('kj', 'Kuanyama; Kwanyama'),
  ('kk', 'Kazakh'),
  ('kl', 'Kalaallisut; Greenlandic'),
  ('km', 'Central Khmer'),
  ('kn', 'Kannada'),
  ('ko', 'Korean'),
  ('kr', 'Kanuri'),
  ('ks', 'Kashmiri'),
  ('ku', 'Kurdish'),
  ('kv', 'Komi'),
  ('kw', 'Cornish'),
  ('ky', 'Kirghiz; Kyrgyz'),
  ('la', 'Latin'),
  ('lb', 'Luxembourgish; Letzeburgesch'),
  ('lg', 'Ganda'),
  ('li', 'Limburgan; Limburger; Limburgish'),
  ('ln', 'Lingala'),
  ('lo', 'Lao'),
  ('lt', 'Lithuanian'),
  ('lu', 'Luba-Katanga'),
  ('lv', 'Latvian'),
  ('mg', 'Malagasy'),
  ('mh', 'Marshallese'),
  ('mi', 'Maori'),
  ('mk', 'Macedonian'),
  ('ml', 'Malayalam'),
  ('mn', 'Mongolian'),
  ('mr', 'Marathi'),
  ('ms', 'Malay'),
  ('mt', 'Maltese'),
  ('my', 'Burmese'),
  ('na', 'Nauru'),
  ('nb', 'Bokmål, Norwegian; Norwegian Bokmål'),
  ('nd', 'Ndebele, North; North Ndebele'),
  ('ne', 'Nepali'),
  ('ng', 'Ndonga'),
  ('nl', 'Dutch; Flemish'),
  ('nn', 'Norwegian Nynorsk; Nynorsk, Norwegian'),
  ('no', 'Norwegian'),
  ('nr', 'Ndebele, South; South Ndebele'),
  ('nv', 'Navajo; Navaho'),
  ('ny', 'Chichewa; Chewa; Nyanja'),
  ('oc', 'Occitan (post 1500)'),
  ('oj', 'Ojibwa'),
  ('om', 'Oromo'),
  ('or', 'Oriya'),
  ('os', 'Ossetian; Ossetic'),
  ('pa', 'Panjabi; Punjabi'),
  ('pi', 'Pali'),
  ('pl', 'Polish'),
  ('ps', 'Pushto; Pashto'),
  ('pt', 'Portuguese'),
  ('qu', 'Quechua'),
  ('rm', 'Romansh'),
  ('rn', 'Rundi'),
  ('ro', 'Romanian; Moldavian; Moldovan'),
  ('ru', 'Russian'),
  ('rw', 'Kinyarwanda'),
  ('sa', 'Sanskrit'),
  ('sc', 'Sardinian'),
  ('sd', 'Sindhi'),
  ('se', 'Northern Sami'),
  ('sg', 'Sango'),
  ('si', 'Sinhala; Sinhalese'),
  ('sk', 'Slovak'),
  ('sl', 'Slovenian'),
  ('sm', 'Samoan'),
  ('sn', 'Shona'),
  ('so', 'Somali'),
  ('sq', 'Albanian'),
  ('sr', 'Serbian'),
  ('ss', 'Swati'),
  ('st', 'Sotho, Southern'),
  ('su', 'Sundanese'),
  ('sv', 'Swedish'),
  ('sw', 'Swahili'),
  ('ta', 'Tamil'),
  ('te', 'Telugu'),
  ('tg', 'Tajik'),
  ('th', 'Thai'),
  ('ti', 'Tigrinya'),
  ('tk', 'Turkmen'),
  ('tl', 'Tagalog'),
  ('tn', 'Tswana'),
  ('to', 'Tonga (Tonga Islands)'),
  ('tr', 'Turkish'),
  ('ts', 'Tsonga'),
  ('tt', 'Tatar'),
  ('tw', 'Twi'),
  ('ty', 'Tahitian'),
  ('ug', 'Uighur; Uyghur'),
  ('uk', 'Ukrainian'),
  ('ur', 'Urdu'),
  ('uz', 'Uzbek'),
  ('ve', 'Venda'),
  ('vi', 'Vietnamese'),
  ('vo', 'Volapük'),
  ('wa', 'Walloon'),
  ('wo', 'Wolof'),
  ('xh', 'Xhosa'),
  ('yi', 'Yiddish'),
  ('yo', 'Yoruba'),
  ('za', 'Zhuang; Chuang'),
  ('zh', 'Chinese'),
  ('zu', 'Zulu')
ON CONFLICT (code) DO NOTHING; 