// This file was automatically generated from the database schema
// Generated at: 2025-06-20T09:15:30.661Z

// Database Tables - Constant names for all database tables
export const TABLES = {
  ACCESS_REQUESTS: 'access_requests',
  ALBUMS: 'albums',
  BUDGET_ITEMS: 'budget_items',
  COLLABORATIVE_NOTES: 'collaborative_notes',
  COLLABORATIVE_SESSIONS: 'collaborative_sessions',
  CONTENT_CUSTOMIZATIONS: 'content_customizations',
  CONTENT_QUALITY_METRICS: 'content_quality_metrics',
  CONTENT_SHARING_HISTORY: 'content_sharing_history',
  CONTENT_SLUGS: 'content_slugs',
  DESTINATION_TAGS: 'destination_tags',
  DESTINATIONS: 'destinations',
  EXPENSES: 'expenses',
  FEEDBACK: 'feedback',
  FOCUS_SESSIONS: 'focus_sessions',
  FORM_COLLABORATORS: 'form_collaborators',
  FORM_TEMPLATES: 'form_templates',
  FORMS: 'forms',
  GROUPS: 'groups',
  GROUP_ACTIVITIES: 'group_activities',
  GROUP_IDEAS: 'group_ideas',
  GROUP_IDEA_NOTES: 'group_idea_notes',
  GROUP_IDEA_VOTES: 'group_idea_votes',
  GROUP_MEMBERS: 'group_members',
  GROUP_TRIPS: 'group_trips',
  IMAGE_METADATA: 'image_metadata',
  INVITATIONS: 'invitations',
  ITEM_POPULARITY_METRICS: 'item_popularity_metrics',
  ITINERARY_ITEM_VOTES: 'itinerary_item_votes',
  ITINERARY_ITEMS: 'itinerary_items',
  ITINERARY_SECTIONS: 'itinerary_sections',
  ITINERARY_TEMPLATE_ITEMS: 'itinerary_template_items',
  ITINERARY_TEMPLATE_SECTIONS: 'itinerary_template_sections',
  ITINERARY_TEMPLATES: 'itinerary_templates',
  LIKES: 'likes',
  LOCATIONS: 'locations',
  NOTE_TAGS: 'note_tags',
  NOTIFICATION_PREFERENCES: 'notification_preferences',
  NOTIFICATIONS: 'notifications',
  ONBOARDING_EVENTS: 'onboarding_events',
  ONBOARDING_TOUR_COMPLETIONS: 'onboarding_tour_completions',
  ONBOARDING_PREFERENCES: 'onboarding_preferences',
  PERMISSION_REQUESTS: 'permission_requests',
  PERFORMANCE_METRICS: 'performance_metrics',
  PLACES: 'places',
  PREFERENCE_WEIGHTS: 'preference_weights',
  PROFILES: 'profiles',
  QUESTION_BRANCHING: 'question_branching',
  QUESTIONS: 'questions',
  REFERRALS: 'referrals',
  RESPONSE_SESSIONS: 'response_sessions',
  RESPONSES: 'responses',
  SURVEY_RESPONSES: 'survey_responses',
  TAGS: 'tags',
  TEMPLATE_APPLICATIONS: 'template_applications',
  TEMPLATE_TAGS: 'template_tags',
  TEAM_INVITATIONS: 'team_invitations',
  TEAM_MEMBERS: 'team_members',
  TEAMS: 'teams',
  TRIP_COMMENT_LIKES: 'trip_comment_likes',
  TRIP_HISTORY: 'trip_history',
  TRIP_IMAGES: 'trip_images',
  TRIP_ITEM_COMMENTS: 'trip_item_comments',
  TRIP_ITEM_VOTES: 'trip_item_votes',
  TRIP_MEMBERS: 'trip_members',
  TRIP_NOTES: 'trip_notes',
  TRIP_SETTINGS: 'trip_settings',
  TRIP_TAGS: 'trip_tags',
  TRIP_TEMPLATE_USES: 'trip_template_uses',
  TRIP_VOTE_OPTIONS: 'trip_vote_options',
  TRIP_VOTE_POLLS: 'trip_vote_polls',
  TRIP_VOTES: 'trip_votes',
  TRIPS: 'trips',
  USER_ACTIVITY: 'user_activity',
  USER_ACTIVITY_DAILY: 'user_activity_daily',
  USER_INTERACTIONS: 'user_interactions',
  USER_INTERESTS: 'user_interests',
  USER_LOGIN_HISTORY: 'user_login_history',
  USER_PREFERENCES: 'user_preferences',
  USER_PRESENCE: 'user_presence',
  USER_SUGGESTED_TAGS: 'user_suggested_tags',
  USER_TRAVEL: 'user_travel',
  USERS: 'users',
  VALIDATION_LOGS: 'validation_logs',
  VOTES: 'votes',
  TRIP_EXPENSES: 'trip_expenses',
  TAG_GROUPS: 'tag_groups',
  TRIP_COMMENTS: 'trip_comments',
  TRIP_ACCESS_REQUESTS: 'trip_access_requests',
  TRIP_LIKES: 'trip_likes',
  DESTINATION_REVIEWS: 'destination_reviews',
  DESTINATION_IMAGES: 'destination_images',
  SETTINGS: 'user_settings',
  ITINERARY_ITEM_REACTIONS: 'itinerary_item_reactions',
  FEATURE_USAGE: 'feature_usage',
  ERROR_LOGS: 'error_logs',
  GROUP_PLANNING_SESSIONS: 'group_planning_sessions',
  PLANNING_READINESS: 'planning_readiness',
  PLANNING_POLLS: 'planning_polls',
  PLANNING_POLL_OPTIONS: 'planning_poll_options',
  PLANNING_POLL_VOTES: 'planning_poll_votes',
  COMMENTS: 'comments',
  COMMENT_REACTIONS: 'comment_reactions',
  REPORTED_CONTENT: 'reported_content',
  MODERATION_LOGS: 'moderation_logs',
  MODERATION_RULES: 'moderation_rules',
  CONTENT_FLAGS: 'content_flags',
  GROUP_IDEA_COMMENTS: 'group_idea_comments',
  GROUP_IDEA_REACTIONS: 'group_idea_reactions',
} as const;

export const FIELDS = {
  COMMON: {
    ID: 'id',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  ACCESS_REQUESTS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    USER_ID: 'user_id',
    REQUESTED_AT: 'requested_at',
    STATUS: 'status',
    APPROVED_BY: 'approved_by',
    APPROVED_AT: 'approved_at',
    MESSAGE: 'message',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  ALBUMS: {
    ID: 'id',
    USER_ID: 'user_id',
    TITLE: 'title',
    DESCRIPTION: 'description',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  BUDGET_ITEMS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    TITLE: 'title',
    AMOUNT: 'amount',
    CURRENCY: 'currency',
    CATEGORY: 'category',
    PAID_BY: 'paid_by',
    DATE: 'date',
    SOURCE: 'source',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  COLLABORATIVE_NOTES: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    TITLE: 'title',
    CONTENT: 'content',
    CREATED_BY: 'created_by',
    IS_PINNED: 'is_pinned',
    LAST_EDITED_BY: 'last_edited_by',
    LAST_EDITED_AT: 'last_edited_at',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  COLLABORATIVE_SESSIONS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    DOCUMENT_TYPE: 'document_type',
    DOCUMENT_ID: 'document_id',
    CONTENT: 'content',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  CONTENT_CUSTOMIZATIONS: {
    ID: 'id',
    ITEM_ID: 'item_id',
    USER_ID: 'user_id',
    CUSTOMIZATION_TYPE: 'customization_type',
    ORIGINAL_VALUE: 'original_value',
    CUSTOMIZED_VALUE: 'customized_value',
    IS_PRIVATE: 'is_private',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    METADATA: 'metadata',
  },
  CONTENT_QUALITY_METRICS: {
    ID: 'id',
    ITEM_ID: 'item_id',
    TRIP_ID: 'trip_id',
    QUALITY_SCORE: 'quality_score',
    ENGAGEMENT_SCORE: 'engagement_score',
    POPULARITY_SCORE: 'popularity_score',
    USAGE_COUNT: 'usage_count',
    LAST_USED_AT: 'last_used_at',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    METADATA: 'metadata',
  },
  CONTENT_SHARING_HISTORY: {
    ID: 'id',
    ITEM_ID: 'item_id',
    SOURCE_TRIP_ID: 'source_trip_id',
    TARGET_TRIP_ID: 'target_trip_id',
    SHARED_BY: 'shared_by',
    SHARED_AT: 'shared_at',
    CUSTOMIZATIONS: 'customizations',
    METADATA: 'metadata',
  },
  CONTENT_SLUGS: {
    ID: 'id',
    CONTENT_TYPE: 'content_type',
    CONTENT_ID: 'content_id',
    SLUG: 'slug',
    IS_CANONICAL: 'is_canonical',
    CREATED_AT: 'created_at',
    CREATED_BY: 'created_by',
  },
  DESTINATION_TAGS: {
    ID: 'id',
    DESTINATION_ID: 'destination_id',
    TAG_ID: 'tag_id',
    ADDED_BY: 'added_by',
    CREATED_AT: 'created_at',
    CONFIDENCE_SCORE: 'confidence_score',
    VOTES_UP: 'votes_up',
    VOTES_DOWN: 'votes_down',
    IS_VERIFIED: 'is_verified',
  },
  DESTINATIONS: {
    ID: 'id',
    NAME: 'name',
    SLUG: 'slug',
    DESCRIPTION: 'description',
    COUNTRY: 'country',
    REGION: 'region',
    CITY: 'city',
    LONGITUDE: 'longitude',
    LATITUDE: 'latitude',
    TIMEZONE: 'timezone',
    IMAGE_URL: 'image_url',
    POPULATION: 'population',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    SHORT_DESCRIPTION: 'short_description',
    IS_PUBLISHED: 'is_published',
    CONTINENT: 'continent',
    LOCATION_HIERARCHY: 'location_hierarchy',
    KNOWN_FOR: 'known_for',
    CLIMATE: 'climate',
    BEST_TIMES_TO_VISIT: 'best_times_to_visit',
    LANGUAGES: 'languages',
    TOP_ATTRACTIONS: 'top_attractions',
    LOCAL_TIPS: 'local_tips',
    FUN_FACTS: 'fun_facts',
    CURRENCY: 'currency',
    SAFETY_INFO: 'safety_info',
    GETTING_AROUND: 'getting_around',
    TAGS: 'tags',
    METADATA: 'metadata',
    CREATED_BY: 'created_by',
    CONTENT_STATUS: 'content_status',
    COVER_IMAGE_URL: 'cover_image_url',
  },
  EXPENSES: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    TITLE: 'title',
    AMOUNT: 'amount',
    CATEGORY: 'category',
    DATE: 'date',
    PAID_BY: 'paid_by',
    CREATED_AT: 'created_at',
    CURRENCY: 'currency',
    SOURCE: 'source',
    UPDATED_AT: 'updated_at',
  },
  FOCUS_SESSIONS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    INITIATED_BY: 'initiated_by',
    SECTION_ID: 'section_id',
    SECTION_PATH: 'section_path',
    SECTION_NAME: 'section_name',
    ACTIVE: 'active',
    MESSAGE: 'message',
    CREATED_AT: 'created_at',
    EXPIRES_AT: 'expires_at',
  },
  IMAGE_METADATA: {
    ID: 'id',
    ENTITY_ID: 'entity_id',
    ENTITY_TYPE: 'entity_type',
    URL: 'url',
    ALT_TEXT: 'alt_text',
    ATTRIBUTION: 'attribution',
    PHOTOGRAPHER_NAME: 'photographer_name',
    PHOTOGRAPHER_URL: 'photographer_url',
    LICENSE: 'license',
    SOURCE: 'source',
    SOURCE_ID: 'source_id',
    WIDTH: 'width',
    HEIGHT: 'height',
    FOCAL_POINT_X: 'focal_point_x',
    FOCAL_POINT_Y: 'focal_point_y',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    ATTRIBUTION_HTML: 'attribution_html',
  },
  INVITATIONS: {
    ID: 'id',
    CREATED_AT: 'created_at',
    INVITED_BY: 'invited_by',
    TRIP_ID: 'trip_id',
    INVITATION_STATUS: 'invitation_status',
    EMAIL: 'email',
    TOKEN: 'token',
    EXPIRES_AT: 'expires_at',
  },
  ITEM_POPULARITY_METRICS: {
    ID: 'id',
    ITEM_ID: 'item_id',
    VIEWS_LAST_24H: 'views_last_24h',
    VIEWS_LAST_7D: 'views_last_7d',
    VIEWS_LAST_30D: 'views_last_30d',
    SHARES_LAST_24H: 'shares_last_24h',
    SHARES_LAST_7D: 'shares_last_7d',
    SHARES_LAST_30D: 'shares_last_30d',
    LIKES_LAST_24H: 'likes_last_24h',
    LIKES_LAST_7D: 'likes_last_7d',
    LIKES_LAST_30D: 'likes_last_30d',
    TRENDING_SCORE: 'trending_score',
    LAST_UPDATED: 'last_updated',
  },
  ITINERARY_ITEM_VOTES: {
    ID: 'id',
    ITINERARY_ITEM_ID: 'itinerary_item_id',
    USER_ID: 'user_id',
    VOTE_TYPE: 'vote_type',
    CREATED_AT: 'created_at',
  },
  ITINERARY_ITEMS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    TITLE: 'title',
    TYPE: 'type',
    DATE: 'date',
    START_TIME: 'start_time',
    END_TIME: 'end_time',
    LOCATION: 'location',
    PLACE_ID: 'place_id',
    LATITUDE: 'latitude',
    LONGITUDE: 'longitude',
    COST: 'cost',
    NOTES: 'notes',
    CREATED_AT: 'created_at',
    CREATED_BY: 'created_by',
    ITEM_TYPE: 'item_type',
    IS_CUSTOM: 'is_custom',
    DAY_NUMBER: 'day_number',
    ADDRESS: 'address',
    CATEGORY: 'category',
    STATUS: 'status',
    POSITION: 'position',
    ESTIMATED_COST: 'estimated_cost',
    CURRENCY: 'currency',
    DURATION_MINUTES: 'duration_minutes',
    SECTION_ID: 'section_id',
    UPDATED_AT: 'updated_at',
    COVER_IMAGE_URL: 'cover_image_url',
    CONTENT_LAYER: 'content_layer',
    ORIGINAL_ID: 'original_id',
    SOURCE_TRIP_ID: 'source_trip_id',
    ATTRIBUTION_TYPE: 'attribution_type',
    ATTRIBUTION_METADATA: 'attribution_metadata',
    SEO_TITLE: 'seo_title',
    SEO_DESCRIPTION: 'seo_description',
    CANONICAL_URL: 'canonical_url',
    SLUG: 'slug',
    META_KEYWORDS: 'meta_keywords',
    STRUCTURED_DATA: 'structured_data',
    SHARE_STATUS: 'share_status',
    SHARE_COUNT: 'share_count',
    LIKE_COUNT: 'like_count',
    VIEW_COUNT: 'view_count',
    VOTES: 'votes',
    LAST_MODIFIED_BY: 'last_modified_by',
    IS_FAVORITE: 'is_favorite',
    DAY: 'day',
  },
  ITINERARY_SECTIONS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    DAY_NUMBER: 'day_number',
    DATE: 'date',
    TITLE: 'title',
    POSITION: 'position',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  ITINERARY_TEMPLATE_ITEMS: {
    ID: 'id',
    TEMPLATE_ID: 'template_id',
    DAY: 'day',
    ITEM_ORDER: 'item_order',
    TITLE: 'title',
    DESCRIPTION: 'description',
    START_TIME: 'start_time',
    END_TIME: 'end_time',
    LOCATION: 'location',
    PLACE_ID: 'place_id',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  ITINERARY_TEMPLATE_SECTIONS: {
    ID: 'id',
    CREATED_AT: 'created_at',
  },
  ITINERARY_TEMPLATES: {
    ID: 'id',
    TITLE: 'title',
    SLUG: 'slug',
    DESCRIPTION: 'description',
    DESTINATION_ID: 'destination_id',
    DURATION_DAYS: 'duration_days',
    CATEGORY: 'category',
    CREATED_BY: 'created_by',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    IS_PUBLISHED: 'is_published',
    VIEW_COUNT: 'view_count',
    USE_COUNT: 'use_count',
    LIKE_COUNT: 'like_count',
    FEATURED: 'featured',
    COVER_IMAGE_URL: 'cover_image_url',
    GROUPSIZE: 'groupsize',
    TAGS: 'tags',
    TEMPLATE_TYPE: 'template_type',
    SOURCE_TRIP_ID: 'source_trip_id',
    VERSION: 'version',
    COPIED_COUNT: 'copied_count',
    LAST_COPIED_AT: 'last_copied_at',
    METADATA: 'metadata',
  },
  LIKES: {
    ID: 'id',
    USER_ID: 'user_id',
    ITEM_ID: 'item_id',
    ITEM_TYPE: 'item_type',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  LOCATIONS: {
    ID: 'id',
    NAME: 'name',
    PARENT_ID: 'parent_id',
    TYPE: 'type',
    CREATED_AT: 'created_at',
  },
  NOTE_TAGS: {
    NOTE_ID: 'note_id',
    TAG_ID: 'tag_id',
    ASSIGNED_AT: 'assigned_at',
  },
  NOTIFICATION_PREFERENCES: {
    ID: 'id',
    USER_ID: 'user_id',
    EMAIL_ENABLED: 'email_enabled',
    PUSH_ENABLED: 'push_enabled',
    IN_APP_ENABLED: 'in_app_enabled',
    TRIP_UPDATES: 'trip_updates',
    ITINERARY_CHANGES: 'itinerary_changes',
    MEMBER_ACTIVITY: 'member_activity',
    COMMENTS: 'comments',
    VOTES: 'votes',
    FOCUS_EVENTS: 'focus_events',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  NOTIFICATIONS: {
    ID: 'id',
    USER_ID: 'user_id',
    TYPE: 'type',
    TITLE: 'title',
    CONTENT: 'content',
    READ: 'read',
    ACTOR_ID: 'actor_id',
    RESOURCE_TYPE: 'resource_type',
    RESOURCE_ID: 'resource_id',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at'
  },
  PERMISSION_REQUESTS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    USER_ID: 'user_id',
    STATUS: 'status',
    MESSAGE: 'message',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  PLACES: {
    ID: 'id',
    NAME: 'name',
    DESCRIPTION: 'description',
    CATEGORY: 'category',
    ADDRESS: 'address',
    LATITUDE: 'latitude',
    LONGITUDE: 'longitude',
    DESTINATION_ID: 'destination_id',
    PRICE_LEVEL: 'price_level',
    RATING: 'rating',
    RATING_COUNT: 'rating_count',
    IMAGES: 'images',
    TAGS: 'tags',
    OPENING_HOURS: 'opening_hours',
    IS_VERIFIED: 'is_verified',
    SUGGESTED_BY: 'suggested_by',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    SOURCE: 'source',
    SOURCE_ID: 'source_id',
  },
  PREFERENCE_WEIGHTS: {
    ID: 'id',
    CATEGORY: 'category',
    SUBCATEGORY: 'subcategory',
    WEIGHT: 'weight',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  PROFILES: {
    ID: 'id',
    UPDATED_AT: 'updated_at',
    NAME: 'name',
    AVATAR_URL: 'avatar_url',
    IS_ADMIN: 'is_admin',
    EMAIL: 'email',
    USERNAME: 'username',
    COVER_IMAGE_URL: 'cover_image_url',
    BIO: 'bio',
    LOCATION: 'location',
    WEBSITE: 'website',
    IS_VERIFIED: 'is_verified',
    HOME_LOCATION_ID: 'home_location_id',
    FIRST_NAME: 'first_name',
    TRAVEL_PERSONALITY: 'travel_personality',
    TRAVEL_SQUAD: 'travel_squad',
    ONBOARDING_COMPLETED: 'onboarding_completed',
    ONBOARDING_COMPLETED_AT: 'onboarding_completed_at',
    ONBOARDING_STEP: 'onboarding_step',
  },
  QUESTIONS: {
    ID: 'id',
    FORM_ID: 'form_id',
    TITLE: 'title',
    DESCRIPTION: 'description',
    PLACEHOLDER: 'placeholder',
    IS_REQUIRED: 'is_required',
    QUESTION_TYPE: 'question_type',
    POSITION: 'position',
    OPTIONS: 'options',
    VALIDATION_RULES: 'validation_rules',
    CONDITIONAL_LOGIC: 'conditional_logic',
    DEFAULT_VALUE: 'default_value',
    MAX_CHARACTER_COUNT: 'max_character_count',
    SHOW_CHARACTER_COUNT: 'show_character_count',
    RATING_SCALE: 'rating_scale',
    RATING_TYPE: 'rating_type',
    ALLOWED_FILE_TYPES: 'allowed_file_types',
    MAX_FILE_SIZE: 'max_file_size',
    MAX_FILES: 'max_files',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  QUESTION_BRANCHING: {
    ID: 'id',
    FORM_ID: 'form_id',
    SOURCE_QUESTION_ID: 'source_question_id',
    TARGET_QUESTION_ID: 'target_question_id',
    CONDITION_TYPE: 'condition_type',
    CONDITION_VALUE: 'condition_value',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  REFERRALS: {
    ID: 'id',
    REFERRER_ID: 'referrer_id',
    REFERRED_ID: 'referred_id',
    REFERRAL_CODE: 'referral_code',
    TRIP_ID: 'trip_id',
    CONVERTED: 'converted',
    CREATED_AT: 'created_at',
    CONVERTED_AT: 'converted_at',
  },
  TAGS: {
    ID: 'id',
    NAME: 'name',
    SLUG: 'slug',
    CATEGORY: 'category',
    EMOJI: 'emoji',
    DESCRIPTION: 'description',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    CREATED_BY: 'created_by',
    IS_VERIFIED: 'is_verified',
    USE_COUNT: 'use_count',
    METADATA: 'metadata',
  },
  TEMPLATE_APPLICATIONS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    TEMPLATE_ID: 'template_id',
    APPLIED_AT: 'applied_at',
    APPLIED_BY: 'applied_by',
    VERSION_USED: 'version_used',
    SUCCESS_RATE: 'success_rate',
    OPTIMIZATION_LEVEL: 'optimization_level',
    FALLBACKS_USED: 'fallbacks_used',
    APPLICATION_METADATA: 'application_metadata',
  },
  TRIP_COMMENT_LIKES: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    COMMENT_ID: 'comment_id',
    USER_ID: 'user_id',
    CREATED_AT: 'created_at',
  },
  TRIP_HISTORY: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    CREATED_AT: 'created_at',
    USER_ID: 'user_id',
    ACTION_TYPE: 'action_type',
    DETAILS: 'details',
  },
  TRIP_IMAGES: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    FILE_PATH: 'file_path',
    FILE_NAME: 'file_name',
    CONTENT_TYPE: 'content_type',
    SIZE_BYTES: 'size_bytes',
    CREATED_BY: 'created_by',
    CREATED_AT: 'created_at',
    WIDTH: 'width',
    HEIGHT: 'height',
    DESCRIPTION: 'description',
    ALBUM_ID: 'album_id',
  },
  TRIP_ITEM_COMMENTS: {
    ID: 'id',
    ITEM_ID: 'item_id',
    TRIP_ID: 'trip_id',
    USER_ID: 'user_id',
    CONTENT: 'content',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  TRIP_MEMBERS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    USER_ID: 'user_id',
    ROLE: 'role',
    JOINED_AT: 'joined_at',
    INVITED_BY: 'invited_by',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  TRIP_NOTES: {
    TRIP_ID: 'trip_id',
    CONTENT: 'content',
    UPDATED_BY: 'updated_by',
    UPDATED_AT: 'updated_at',
    USER_ID: 'user_id',
    ALBUM_ID: 'album_id',
    ID: 'id',
    TITLE: 'title',
  },
  TRIP_TAGS: {
    TRIP_ID: 'trip_id',
    TAG_ID: 'tag_id',
    ASSIGNED_AT: 'assigned_at',
  },
  TRIP_TEMPLATE_USES: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    TEMPLATE_ID: 'template_id',
    APPLIED_AT: 'applied_at',
    APPLIED_BY: 'applied_by',
    VERSION_USED: 'version_used',
    MODIFICATIONS: 'modifications',
  },
  TRIP_VOTE_OPTIONS: {
    ID: 'id',
    POLL_ID: 'poll_id',
    TITLE: 'title',
    DESCRIPTION: 'description',
    IMAGE_URL: 'image_url',
    CREATED_AT: 'created_at',
  },
  TRIP_VOTE_POLLS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    TITLE: 'title',
    DESCRIPTION: 'description',
    IS_ACTIVE: 'is_active',
    CREATED_BY: 'created_by',
    EXPIRES_AT: 'expires_at',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  TRIP_VOTES: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    POLL_ID: 'poll_id',
    OPTION_ID: 'option_id',
    USER_ID: 'user_id',
    CREATED_AT: 'created_at',
  },
  TRIPS: {
    ID: 'id',
    TITLE: 'title',
    DESCRIPTION: 'description',
    START_DATE: 'start_date',
    END_DATE: 'end_date',
    CREATED_BY: 'created_by',
    IS_PUBLIC: 'is_public',
    PRIVACY_SETTING: 'privacy_setting',
    LOCATION: 'location',
    TRIP_TYPE: 'trip_type',
    STATUS: 'status',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    PLANNING_SESSION_ID: 'planning_session_id',
    FROM_PLANNING: 'from_planning',
    TOUR_COMPLETED: 'tour_completed',
  },
  USER_ACTIVITY: {
    ID: 'id',
    USER_ID: 'user_id',
    SESSION_ID: 'session_id',
    EVENT_TYPE: 'event_type',
    ENTITY_TYPE: 'entity_type',
    ENTITY_ID: 'entity_id',
    ACTION: 'action',
    IP_ADDRESS: 'ip_address',
    USER_AGENT: 'user_agent',
    REFERRER: 'referrer',
    PATH: 'path',
    METADATA: 'metadata',
    CREATED_AT: 'created_at',
  },
  USER_ACTIVITY_DAILY: {
    ID: 'id',
    USER_ID: 'user_id',
    DATE: 'date',
    ACTIVITY_COUNT: 'activity_count',
    METADATA: 'metadata',
    CREATED_AT: 'created_at',
  },
  USER_INTERACTIONS: {
    ID: 'id',
    USER_ID: 'user_id',
    DESTINATION_ID: 'destination_id',
    INTERACTION_TYPE: 'interaction_type',
    CREATED_AT: 'created_at',
  },
  USER_INTERESTS: {
    ID: 'id',
    USER_ID: 'user_id',
    TAG_ID: 'tag_id',
    STRENGTH: 'strength',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  USER_LOGIN_HISTORY: {
    ID: 'id',
    USER_ID: 'user_id',
    LOGIN_AT: 'login_at',
    IP_ADDRESS: 'ip_address',
    USER_AGENT: 'user_agent',
    SUCCESS: 'success',
    METHOD: 'method',
    CREATED_AT: 'created_at',
  },
  USER_PREFERENCES: {
    ID: 'id',
    USER_ID: 'user_id',
    TRAVEL_STYLES: 'travel_styles',
    PREFERRED_PACE: 'preferred_pace',
    BUDGET_RANGE: 'budget_range',
    PREFERRED_ACTIVITY_TYPES: 'preferred_activity_types',
    PREFERRED_TIMES_OF_DAY: 'preferred_times_of_day',
    ACCESSIBILITY_NEEDS: 'accessibility_needs',
    DIETARY_RESTRICTIONS: 'dietary_restrictions',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    METADATA: 'metadata',
  },
  USER_PRESENCE: {
    ID: 'id',
    USER_ID: 'user_id',
    TRIP_ID: 'trip_id',
    DOCUMENT_ID: 'document_id',
    STATUS: 'status',
    LAST_ACTIVE: 'last_active',
  },
  USER_SUGGESTED_TAGS: {
    ID: 'id',
    USER_ID: 'user_id',
    DESTINATION_ID: 'destination_id',
    NAME: 'name',
    SLUG: 'slug',
    CATEGORY: 'category',
    STATUS: 'status',
    ADMIN_NOTES: 'admin_notes',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  USER_TRAVEL: {
    USER_ID: 'user_id',
    DESTINATION_ID: 'destination_id',
    VISITED_AT: 'visited_at',
  },
  USERS: {
    ID: 'id',
    EMAIL: 'email',
    NAME: 'name',
    AVATAR_URL: 'avatar_url',
    CREATED_AT: 'created_at',
    IS_ADMIN: 'is_admin',
    BIO: 'bio',
    LOCATION: 'location',
    INTERESTS: 'interests',
    UPDATED_AT: 'updated_at',
    USERNAME: 'username',
    FULL_NAME: 'full_name',
    LAST_SIGN_IN_AT: 'last_sign_in_at',
  },
  VALIDATION_LOGS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    TEMPLATE_ID: 'template_id',
    IS_VALID: 'is_valid',
    VALIDATION_ERRORS: 'validation_errors',
    VALIDATED_AT: 'validated_at',
    VALIDATED_BY: 'validated_by',
  },
  VOTES: {
    ID: 'id',
    ITINERARY_ITEM_ID: 'itinerary_item_id',
    USER_ID: 'user_id',
    VOTE_TYPE: 'vote_type',
    CREATED_AT: 'created_at',
  },
  TEMPLATE_TAGS: {
    ID: 'id',
    TEMPLATE_ID: 'template_id',
    TAG_ID: 'tag_id',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  TRIP_SETTINGS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    SETTING_TYPE: 'setting_type',
    VALUE: 'value',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  TEAM_INVITATIONS: {
    ID: 'id',
    TEAM_ID: 'team_id',
    INVITED_BY: 'invited_by',
    INVITATION_STATUS: 'invitation_status',
    EMAIL: 'email',
    TOKEN: 'token',
    EXPIRES_AT: 'expires_at',
  },
  TEAM_MEMBERS: {
    ID: 'id',
    TEAM_ID: 'team_id',
    USER_ID: 'user_id',
    ROLE: 'role',
    CREATED_AT: 'created_at',
    INVITED_BY: 'invited_by',
    JOINED_AT: 'joined_at',
  },
  TEAMS: {
    ID: 'id',
    NAME: 'name',
    DESCRIPTION: 'description',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  ITINERARY_ITEM_REACTIONS: {
    ID: 'id',
    ITINERARY_ITEM_ID: 'itinerary_item_id',
    USER_ID: 'user_id',
    EMOJI: 'emoji',
    CREATED_AT: 'created_at',
  },
  GROUPS: {
    ID: 'id',
    NAME: 'name',
    SLUG: 'slug',
    EMOJI: 'emoji',
    DESCRIPTION: 'description',
    CREATED_BY: 'created_by',
    VISIBILITY: 'visibility',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  GROUP_MEMBERS: {
    GROUP_ID: 'group_id',
    USER_ID: 'user_id',
    ROLE: 'role',
    STATUS: 'status',
    INVITATION_EMAIL: 'invitation_email',
    INVITATION_TOKEN: 'invitation_token',
    INVITATION_EXPIRES_AT: 'invitation_expires_at',
    JOINED_AT: 'joined_at',
    UPDATED_AT: 'updated_at',
  },
  GROUP_TRIPS: {
    GROUP_ID: 'group_id',
    TRIP_ID: 'trip_id',
    ADDED_BY: 'added_by',
    NOTES: 'notes',
    IS_FEATURED: 'is_featured',
    DISPLAY_ORDER: 'display_order',
    ADDED_AT: 'added_at',
    UPDATED_AT: 'updated_at',
  },
  GROUP_ACTIVITIES: {
    ID: 'id',
    GROUP_ID: 'group_id',
    USER_ID: 'user_id',
    ACTIVITY_TYPE: 'activity_type',
    TRIP_ID: 'trip_id',
    DETAILS: 'details',
    CREATED_AT: 'created_at',
  },
  ONBOARDING_EVENTS: {
    ID: 'id',
    USER_ID: 'user_id',
    EVENT_TYPE: 'event_type',
    TOUR_ID: 'tour_id',
    STEP_ID: 'step_id',
    EVENT_DATA: 'event_data',
    SESSION_ID: 'session_id',
    CREATED_AT: 'created_at',
  },
  ONBOARDING_TOUR_COMPLETIONS: {
    ID: 'id',
    USER_ID: 'user_id',
    TOUR_ID: 'tour_id',
    COMPLETED_AT: 'completed_at',
    IS_SKIPPED: 'is_skipped',
    TIME_SPENT: 'time_spent',
    STEPS_VIEWED: 'steps_viewed',
  },
  ONBOARDING_PREFERENCES: {
    ID: 'id',
    USER_ID: 'user_id',
    FEATURE_ID: 'feature_id',
    IS_ENABLED: 'is_enabled',
    SHOW_TOURS: 'show_tours',
    NOTIFICATION_LEVEL: 'notification_level',
    PREFERENCES: 'preferences',
    UPDATED_AT: 'updated_at',
  },
  FEATURE_USAGE: {
    ID: 'id',
    FEATURE_ID: 'feature_id',
    USER_ID: 'user_id',
    ENTITY_ID: 'entity_id',
    ACTION: 'action',
    VALUE: 'value',
    CONTEXT: 'context',
    METADATA: 'metadata',
    CREATED_AT: 'created_at',
  },
  ERROR_LOGS: {
    ID: 'id',
    USER_ID: 'user_id',
    SESSION_ID: 'session_id',
    ERROR_TYPE: 'error_type',
    ERROR_MESSAGE: 'error_message',
    ERROR_STACK: 'error_stack',
    URL: 'url',
    PATH: 'path',
    COMPONENT: 'component',
    SEVERITY: 'severity',
    BROWSER: 'browser',
    OS: 'os',
    DEVICE: 'device',
    METADATA: 'metadata',
    CREATED_AT: 'created_at',
  },
  GROUP_IDEAS: {
    ID: 'id',
    GROUP_ID: 'group_id',
    TITLE: 'title',
    DESCRIPTION: 'description',
    TYPE: 'type',
    CREATED_BY: 'created_by',
    GUEST_TOKEN: 'guest_token',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    VOTES_UP: 'votes_up',
    VOTES_DOWN: 'votes_down',
    POSITION: 'position',
    SELECTED: 'selected',
    META: 'meta',
  },
  GROUP_IDEA_NOTES: {
    ID: 'id',
    IDEA_ID: 'idea_id',
    CONTENT: 'content',
    CREATED_BY: 'created_by',
    GUEST_TOKEN: 'guest_token',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  GROUP_IDEA_VOTES: {
    ID: 'id',
    IDEA_ID: 'idea_id',
    USER_ID: 'user_id',
    GUEST_TOKEN: 'guest_token',
    VOTE_TYPE: 'vote_type',
    CREATED_AT: 'created_at',
  },
  GROUP_PLANNING_SESSIONS: {
    ID: 'id',
    GROUP_ID: 'group_id',
    NAME: 'name',
    STATUS: 'status',
    DESTINATION: 'destination',
    DATE_RANGE: 'date_range',
    BUDGET: 'budget',
    ACTIVITIES: 'activities',
    TRIP_ID: 'trip_id',
    CREATED_BY: 'created_by',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    COMPLETED_AT: 'completed_at',
    EXPORTED_AT: 'exported_at',
  },
  PLANNING_READINESS: {
    ID: 'id',
    SESSION_ID: 'session_id',
    USER_ID: 'user_id',
    GUEST_TOKEN: 'guest_token',
    IS_READY: 'is_ready',
    READY_AT: 'ready_at',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  PLANNING_POLLS: {
    ID: 'id',
    SESSION_ID: 'session_id',
    QUESTION: 'question',
    TYPE: 'type',
    MULTI_SELECT: 'multi_select',
    CREATED_AT: 'created_at',
  },
  PLANNING_POLL_OPTIONS: {
    ID: 'id',
    POLL_ID: 'poll_id',
    TEXT: 'text',
    IDEA_ID: 'idea_id',
    CREATED_AT: 'created_at',
  },
  PLANNING_POLL_VOTES: {
    ID: 'id',
    OPTION_ID: 'option_id',
    USER_ID: 'user_id',
    GUEST_TOKEN: 'guest_token',
    CREATED_AT: 'created_at',
  },
  COMMENTS: {
    ID: 'id',
    CONTENT: 'content',
    USER_ID: 'user_id',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    PARENT_ID: 'parent_id',
    CONTENT_TYPE: 'content_type',
    CONTENT_ID: 'content_id',
    IS_EDITED: 'is_edited',
    IS_DELETED: 'is_deleted',
    REACTIONS_COUNT: 'reactions_count',
    REPLIES_COUNT: 'replies_count',
    ATTACHMENT_URL: 'attachment_url',
    ATTACHMENT_TYPE: 'attachment_type',
    METADATA: 'metadata',
  },
  COMMENT_REACTIONS: {
    ID: 'id',
    COMMENT_ID: 'comment_id',
    USER_ID: 'user_id',
    EMOJI: 'emoji',
    CREATED_AT: 'created_at',
  },
  REPORTED_CONTENT: {
    ID: 'id',
    CONTENT_TYPE: 'content_type',
    CONTENT_ID: 'content_id',
    REPORTER_ID: 'reporter_id',
    REASON: 'reason',
    STATUS: 'status',
    CREATED_AT: 'created_at',
    RESOLVED_AT: 'resolved_at',
    RESOLVER_ID: 'resolver_id',
    RESOLUTION_NOTES: 'resolution_notes',
    ENCRYPTED_CONTENT_SNAPSHOT: 'encrypted_content_snapshot'
  },
  MODERATION_LOGS: {
    ID: 'id',
    MODERATOR_ID: 'moderator_id',
    ACTION: 'action',
    TARGET_TYPE: 'target_type',
    TARGET_ID: 'target_id',
    NOTES: 'notes',
    CREATED_AT: 'created_at'
  },
  GROUP_IDEA_COMMENTS: {
    ID: 'id',
    IDEA_ID: 'idea_id',
    USER_ID: 'user_id',
    CONTENT: 'content',
    PARENT_ID: 'parent_id',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    IS_EDITED: 'is_edited',
    IS_DELETED: 'is_deleted',
    REACTIONS_COUNT: 'reactions_count',
    REPLIES_COUNT: 'replies_count',
    ATTACHMENT_URL: 'attachment_url',
    ATTACHMENT_TYPE: 'attachment_type',
    METADATA: 'metadata',
  },
  GROUP_IDEA_REACTIONS: {
    ID: 'id',
    IDEA_ID: 'idea_id',
    USER_ID: 'user_id',
    COMMENT_ID: 'comment_id',
    EMOJI: 'emoji',
    CREATED_AT: 'created_at',
  },
} as const;

export const ENUMS = {
  TRIP_ROLES: {
    ADMIN: 'admin',
    EDITOR: 'editor',
    CONTRIBUTOR: 'contributor',
    VIEWER: 'viewer',
  },
  GROUP_ROLES: {
    OWNER: 'owner',
    ADMIN: 'admin',
    MEMBER: 'member',
  },
  GROUP_MEMBER_STATUS: {
    INVITED: 'invited',
    ACTIVE: 'active',
    LEFT: 'left',
    REMOVED: 'removed',
  },
  GROUP_ACTIVITY_TYPE: {
    TRIP_ADDED: 'trip_added',
    TRIP_REMOVED: 'trip_removed',
    MEMBER_JOINED: 'joined_group',
    MEMBER_LEFT: 'left_group',
    INVITE_SENT: 'invite_sent',
    OWNERSHIP_TRANSFERRED: 'ownership_transferred',
    GROUP_UPDATED: 'group_updated',
  },
  ITEM_STATUS: {
    SUGGESTED: 'suggested',
    CONFIRMED: 'confirmed',
    REJECTED: 'rejected',
  },
  TRIP_STATUS: {
    PLANNING: 'planning',
    UPCOMING: 'upcoming',
    IN_PROGRESS: 'in_progress',
    COMPLETED: 'completed',
    CANCELLED: 'cancelled',
  },
  PERMISSION_STATUS: {
    PENDING: 'pending',
    APPROVED: 'approved',
    DENIED: 'denied',
  },
  IMAGE_TYPE: {
    DESTINATION: 'destination',
    TRIP_COVER: 'trip_cover',
    USER_AVATAR: 'user_avatar',
    TEMPLATE_COVER: 'template_cover',
    GROUP_COVER: 'group_cover',
  },
  CONTENT_TYPE: {
    TRIP: 'trip',
    ITINERARY_ITEM: 'itinerary_item',
    DESTINATION: 'destination',
    COLLECTION: 'collection',
    TEMPLATE: 'template',
    GROUP: 'group',
    COMMENT: 'comment',
    PROFILE: 'profile',
    TRIP_DESCRIPTION: 'trip_description'
  },
  QUESTION_TYPE: {
    TEXT: 'text',
    SELECT: 'select',
    MULTI_SELECT: 'multi_select',
    DATE: 'date',
    NUMBER: 'number',
    BOOLEAN: 'boolean',
  },
  FORM_STATUS: {
    DRAFT: 'draft',
    PUBLISHED: 'published',
    ARCHIVED: 'archived',
  },
  FORM_VISIBILITY: {
    PUBLIC: 'public',
    PRIVATE: 'private',
    SHARED: 'shared',
  },
  ITINERARY_CATEGORY: {
    ICONIC_LANDMARKS: 'Iconic Landmarks',
    LOCAL_SECRETS: 'Local Secrets',
    CULTURAL_EXPERIENCES: 'Cultural Experiences',
    OUTDOOR_ADVENTURES: 'Outdoor Adventures',
    FOOD_AND_DRINK: 'Food & Drink',
    NIGHTLIFE: 'Nightlife',
    RELAXATION: 'Relaxation',
    SHOPPING: 'Shopping',
    GROUP_ACTIVITIES: 'Group Activities',
    DAY_EXCURSIONS: 'Day Excursions',
    ACCOMMODATIONS: 'Accommodations',
    TRANSPORTATION: 'Transportation',
    FLEXIBLE_OPTIONS: 'Flexible Options',
    SPECIAL_OCCASIONS: 'Special Occasions',
    OTHER: 'Other',
  },
  ITINERARY_ITEM_STATUS: {
    PENDING: 'pending',
    APPROVED: 'approved',
    REJECTED: 'rejected',
  },
  INVITATION_STATUS: {
    PENDING: 'pending',
    ACCEPTED: 'accepted',
    DECLINED: 'declined',
    EXPIRED: 'expired',
  },
  PRIVACY_SETTING: {
    PRIVATE: 'private',
    SHARED_WITH_LINK: 'shared_with_link',
    PUBLIC: 'public',
  },
  TRIP_PRIVACY_SETTING: {
    PRIVATE: 'private',
    SHARED_WITH_LINK: 'shared_with_link',
    PUBLIC: 'public',
  },
  PLACE_CATEGORY: {
    ATTRACTION: 'attraction',
    RESTAURANT: 'restaurant',
    CAFE: 'cafe',
    HOTEL: 'hotel',
    LANDMARK: 'landmark',
    SHOPPING: 'shopping',
    TRANSPORT: 'transport',
    OTHER: 'other',
  },
  TAG_STATUS: {
    PENDING: 'pending',
    APPROVED: 'approved',
    REJECTED: 'rejected',
  },
  TRAVEL_PACE: {
    VERY_SLOW: 'very_slow',
    SLOW: 'slow',
    MODERATE: 'moderate',
    FAST: 'fast',
    VERY_FAST: 'very_fast',
  },
  TRAVEL_PERSONALITY_TYPE: {
    PLANNER: 'planner',
    ADVENTURER: 'adventurer',
    FOODIE: 'foodie',
    SIGHTSEER: 'sightseer',
    RELAXER: 'relaxer',
    CULTURE: 'culture',
  },
  TRAVEL_SQUAD_TYPE: {
    FRIENDS: 'friends',
    FAMILY: 'family',
    PARTNER: 'partner',
    SOLO: 'solo',
    COWORKERS: 'coworkers',
    MIXED: 'mixed',
  },
  TRAVEL_STYLE: {
    ADVENTUROUS: 'adventurous',
    RELAXED: 'relaxed',
    CULTURAL: 'cultural',
    LUXURY: 'luxury',
    BUDGET: 'budget',
    FAMILY: 'family',
    SOLO: 'solo',
    NIGHTLIFE: 'nightlife',
    NATURE: 'nature',
    FOOD_FOCUSED: 'food_focused',
  },
  BUDGET_CATEGORY: {
    ACCOMMODATION: 'accommodation',
    TRANSPORTATION: 'transportation',
    FOOD: 'food',
    ACTIVITIES: 'activities',
    SHOPPING: 'shopping',
    OTHER: 'other',
  },
  TRIP_TYPE: {
    LEISURE: 'leisure',
    BUSINESS: 'business',
    FAMILY: 'family',
    SOLO: 'solo',
    GROUP: 'group',
    OTHER: 'other',
  },
  VOTE_TYPE: {
    UP: 'up',
    DOWN: 'down',
    THUMBS_UP: '👍',
    THUMBS_DOWN: '👎',
    HEART: '❤️',
    QUESTION: '❓',
  },
  INTERACTION_TYPE: {
    LIKE: 'like',
    VISIT: 'visit',
    BOOKMARK: 'bookmark',
    TAG: 'tag',
  },
  URL_FORMAT: {
    CANONICAL: 'canonical',
    SHORT: 'short',
  },
  TRIP_ACTION_TYPE: {
    CREATED: 'created',
    UPDATED_DETAILS: 'updated_details',
    ADDED_MEMBER: 'added_member',
    REMOVED_MEMBER: 'removed_member',
    ADDED_TRIP_ITEM: 'added_trip_item',
    REMOVED_TRIP_ITEM: 'removed_trip_item',
    UPDATED_TRIP_ITEM: 'updated_trip_item',
    SHARED: 'shared',
    UNSHARED: 'unshared',
  },
  ERROR_SEVERITY: {
    INFO: 'info',
    WARNING: 'warning',
    ERROR: 'error',
    CRITICAL: 'critical',
  },
  ONBOARDING_EVENT_TYPE: {
    TOUR_STARTED: 'tour_started',
    TOUR_COMPLETED: 'tour_completed',
    TOUR_SKIPPED: 'tour_skipped',
    STEP_VIEWED: 'step_viewed',
    STEP_COMPLETED: 'step_completed',
    ONBOARDING_COMPLETED: 'onboarding_completed',
    STEP_CHANGED: 'step_changed',
  },
  IDEA_TYPES: {
    DESTINATION: 'destination',
    DATE: 'date',
    ACTIVITY: 'activity',
    BUDGET: 'budget',
    OTHER: 'other',
  },
  PLANNING_SESSION_STATUSES: {
    DRAFT: 'draft',
    IN_PROGRESS: 'in_progress',
    VOTING: 'voting',
    COMPLETED: 'completed',
    CONVERTED: 'converted',
  },
  CONTENT_TYPES: {
    DESTINATION: 'destination',
    GROUP_IDEA: 'group_idea',
    ITINERARY_ITEM: 'itinerary_item',
    TRIP: 'trip',
    IMAGE: 'image',
    NOTE: 'note',
  },
  NOTIFICATION_TYPES: {
    COMMENT: 'comment',
    MENTION: 'mention',
    TRIP_INVITE: 'trip_invite',
    TRIP_UPDATE: 'trip_update',
    NEW_MEMBER: 'new_member',
    ITINERARY_CHANGE: 'itinerary_change',
    SYSTEM_MESSAGE: 'system_message'
  },
  MODERATION_STATUS: {
    PENDING: 'pending',
    APPROVED: 'approved',
    REJECTED: 'rejected', 
    ESCALATED: 'escalated'
  }
} as const;

// Add a new export type for GroupRole from the ENUMS object
export type GroupRole = (typeof ENUMS.GROUP_ROLES)[keyof typeof ENUMS.GROUP_ROLES];

// Add a new export type for GroupMemberStatus from the ENUMS object
export type GroupMemberStatus = (typeof ENUMS.GROUP_MEMBER_STATUS)[keyof typeof ENUMS.GROUP_MEMBER_STATUS];

// Add a new export type for GroupActivityType from the ENUMS object
export type GroupActivityType = (typeof ENUMS.GROUP_ACTIVITY_TYPE)[keyof typeof ENUMS.GROUP_ACTIVITY_TYPE];

// Add a new export type for OnboardingEventType from the ENUMS object
export type OnboardingEventType = (typeof ENUMS.ONBOARDING_EVENT_TYPE)[keyof typeof ENUMS.ONBOARDING_EVENT_TYPE];

// Add a new export type for ErrorSeverity from the ENUMS object
export type ErrorSeverity = (typeof ENUMS.ERROR_SEVERITY)[keyof typeof ENUMS.ERROR_SEVERITY];

export type TripRole = (typeof ENUMS.TRIP_ROLES)[keyof typeof ENUMS.TRIP_ROLES];
export type ItemStatus = (typeof ENUMS.ITEM_STATUS)[keyof typeof ENUMS.ITEM_STATUS];
export type TripStatus = (typeof ENUMS.TRIP_STATUS)[keyof typeof ENUMS.TRIP_STATUS];
export type PermissionStatus =
  (typeof ENUMS.PERMISSION_STATUS)[keyof typeof ENUMS.PERMISSION_STATUS];

export type ImageType = (typeof ENUMS.IMAGE_TYPE)[keyof typeof ENUMS.IMAGE_TYPE];
export type ContentItemType = (typeof ENUMS.CONTENT_TYPE)[keyof typeof ENUMS.CONTENT_TYPE];
export type QuestionType = (typeof ENUMS.QUESTION_TYPE)[keyof typeof ENUMS.QUESTION_TYPE];
export type FormStatus = (typeof ENUMS.FORM_STATUS)[keyof typeof ENUMS.FORM_STATUS];
export type FormVisibility = (typeof ENUMS.FORM_VISIBILITY)[keyof typeof ENUMS.FORM_VISIBILITY];
export type ItineraryCategory =
  (typeof ENUMS.ITINERARY_CATEGORY)[keyof typeof ENUMS.ITINERARY_CATEGORY];

export type ItineraryItemStatus = (typeof ENUMS.ITINERARY_ITEM_STATUS)[keyof typeof ENUMS.ITINERARY_ITEM_STATUS];
export type InvitationStatus = (typeof ENUMS.INVITATION_STATUS)[keyof typeof ENUMS.INVITATION_STATUS];
export type PrivacySetting = (typeof ENUMS.PRIVACY_SETTING)[keyof typeof ENUMS.PRIVACY_SETTING];
export type TripPrivacySetting = (typeof ENUMS.TRIP_PRIVACY_SETTING)[keyof typeof ENUMS.TRIP_PRIVACY_SETTING];
export type PlaceCategory = (typeof ENUMS.PLACE_CATEGORY)[keyof typeof ENUMS.PLACE_CATEGORY];
export type TagStatus = (typeof ENUMS.TAG_STATUS)[keyof typeof ENUMS.TAG_STATUS];
export type TravelPace = (typeof ENUMS.TRAVEL_PACE)[keyof typeof ENUMS.TRAVEL_PACE];
export type TravelPersonalityType = (typeof ENUMS.TRAVEL_PERSONALITY_TYPE)[keyof typeof ENUMS.TRAVEL_PERSONALITY_TYPE];
export type TravelSquadType = (typeof ENUMS.TRAVEL_SQUAD_TYPE)[keyof typeof ENUMS.TRAVEL_SQUAD_TYPE];
export type TravelStyle = (typeof ENUMS.TRAVEL_STYLE)[keyof typeof ENUMS.TRAVEL_STYLE];
export type BudgetCategory = (typeof ENUMS.BUDGET_CATEGORY)[keyof typeof ENUMS.BUDGET_CATEGORY];
export type TripType = (typeof ENUMS.TRIP_TYPE)[keyof typeof ENUMS.TRIP_TYPE];
export type VoteType = (typeof ENUMS.VOTE_TYPE)[keyof typeof ENUMS.VOTE_TYPE];
export type InteractionType = (typeof ENUMS.INTERACTION_TYPE)[keyof typeof ENUMS.INTERACTION_TYPE];
export type UrlFormat = (typeof ENUMS.URL_FORMAT)[keyof typeof ENUMS.URL_FORMAT];
export type TripActionType = (typeof ENUMS.TRIP_ACTION_TYPE)[keyof typeof ENUMS.TRIP_ACTION_TYPE];
export type IdeaType = (typeof ENUMS.IDEA_TYPES)[keyof typeof ENUMS.IDEA_TYPES];
export type PlanningSessionStatus = (typeof ENUMS.PLANNING_SESSION_STATUSES)[keyof typeof ENUMS.PLANNING_SESSION_STATUSES];

export type TableNames = (typeof TABLES)[keyof typeof TABLES];
export type TableFields<T extends keyof typeof FIELDS> =
  (typeof FIELDS)[T][keyof (typeof FIELDS)[T]];

const ITINERARY_TEMPLATE_METADATA_FIELDS = {
  PACE: 'pace',
  BEST_FOR: 'best_for',
  LANGUAGES: 'languages',
  HIGHLIGHTS: 'highlights',
  LOCAL_TIPS: 'local_tips',
  BEST_SEASONS: 'best_seasons',
  AVOID_SEASONS: 'avoid_seasons',
  MORNING_START: 'morning_start',
  ACCESSIBILITY_LEVEL: 'accessibility_level',
  SUSTAINABILITY_ASPECTS: 'sustainability_aspects',
  ESTIMATED_BUDGET_USD_PER_DAY: 'estimated_budget_usd_per_day',
};

export type ItineraryTemplateMetadata = {
  pace: string;
  best_for: string[];
  languages: string[];
  highlights: string[];
  local_tips: string[];
  best_seasons: string[];
  avoid_seasons: string[];
  morning_start: string;
  accessibility_level: string;
  sustainability_aspects: string[];
  estimated_budget_usd_per_day: number;
};

// Change our new type to CommentableContentType
export type CommentableContentType = (typeof ENUMS.CONTENT_TYPES)[keyof typeof ENUMS.CONTENT_TYPES];
