// This file was automatically generated from the database schema
// Generated at: 2025-06-20T09:15:30.661Z

// Database Tables - Constant names for all database tables
export const TABLES = {
  ACCESS_REQUESTS: 'access_requests',
  ALBUMS: 'albums',
  BUDGET_ITEMS: 'budget_items',
  COLLABORATIVE_NOTES: 'collaborative_notes',
  COLLABORATIVE_SESSIONS: 'collaborative_sessions',
  CONTENT_CUSTOMIZATIONS: 'content_customizations',
  CONTENT_QUALITY_METRICS: 'content_quality_metrics',
  CONTENT_SHARING_HISTORY: 'content_sharing_history',
  CONTENT_SLUGS: 'content_slugs',
  DESTINATION_TAGS: 'destination_tags',
  DESTINATIONS: 'destinations',
  EXPENSES: 'expenses',
  FOCUS_SESSIONS: 'focus_sessions',
  FORM_COLLABORATORS: 'form_collaborators',
  FORM_TEMPLATES: 'form_templates',
  FORMS: 'forms',
  IMAGE_METADATA: 'image_metadata',
  INVITATIONS: 'invitations',
  ITEM_POPULARITY_METRICS: 'item_popularity_metrics',
  ITINERARY_ITEM_VOTES: 'itinerary_item_votes',
  ITINERARY_ITEMS: 'itinerary_items',
  ITINERARY_SECTIONS: 'itinerary_sections',
  ITINERARY_TEMPLATE_ITEMS: 'itinerary_template_items',
  ITINERARY_TEMPLATE_SECTIONS: 'itinerary_template_sections',
  ITINERARY_TEMPLATES: 'itinerary_templates',
  LIKES: 'likes',
  LOCATIONS: 'locations',
  NOTE_TAGS: 'note_tags',
  NOTIFICATION_PREFERENCES: 'notification_preferences',
  NOTIFICATIONS: 'notifications',
  PERMISSION_REQUESTS: 'permission_requests',
  PLACES: 'places',
  PREFERENCE_WEIGHTS: 'preference_weights',
  PROFILES: 'profiles',
  QUESTION_BRANCHING: 'question_branching',
  QUESTIONS: 'questions',
  REFERRALS: 'referrals',
  RESPONSE_SESSIONS: 'response_sessions',
  RESPONSES: 'responses',
  SURVEY_RESPONSES: 'survey_responses',
  TAGS: 'tags',
  TEMPLATE_APPLICATIONS: 'template_applications',
  TEMPLATE_TAGS: 'template_tags',
  TEAM_INVITATIONS: 'team_invitations',
  TEAM_MEMBERS: 'team_members',
  TEAMS: 'teams',
  TRIP_COMMENT_LIKES: 'trip_comment_likes',
  TRIP_HISTORY: 'trip_history',
  TRIP_IMAGES: 'trip_images',
  TRIP_ITEM_COMMENTS: 'trip_item_comments',
  TRIP_ITEM_VOTES: 'trip_item_votes',
  TRIP_MEMBERS: 'trip_members',
  TRIP_NOTES: 'trip_notes',
  TRIP_SETTINGS: 'trip_settings',
  TRIP_TAGS: 'trip_tags',
  TRIP_TEMPLATE_USES: 'trip_template_uses',
  TRIP_VOTE_OPTIONS: 'trip_vote_options',
  TRIP_VOTE_POLLS: 'trip_vote_polls',
  TRIP_VOTES: 'trip_votes',
  TRIPS: 'trips',
  USER_ACTIVITY_HISTORY: 'user_activity_history',
  USER_INTERACTIONS: 'user_interactions',
  USER_INTERESTS: 'user_interests',
  USER_LOGIN_HISTORY: 'user_login_history',
  USER_PREFERENCES: 'user_preferences',
  USER_PRESENCE: 'user_presence',
  USER_SUGGESTED_TAGS: 'user_suggested_tags',
  USER_TRAVEL: 'user_travel',
  USERS: 'users',
  VALIDATION_LOGS: 'validation_logs',
  VOTES: 'votes',
  TRIP_EXPENSES: 'trip_expenses',
  TAG_GROUPS: 'tag_groups',
  TRIP_COMMENTS: 'trip_comments',
  TRIP_ACCESS_REQUESTS: 'trip_access_requests',
  TRIP_LIKES: 'trip_likes',
  DESTINATION_REVIEWS: 'destination_reviews',
  DESTINATION_IMAGES: 'destination_images',
  SETTINGS: 'user_settings',
  ITINERARY_ITEM_REACTIONS: 'itinerary_item_reactions',
} as const;

export const FIELDS = {
  COMMON: {
    ID: 'id',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  ACCESS_REQUESTS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    USER_ID: 'user_id',
    REQUESTED_AT: 'requested_at',
    STATUS: 'status',
    APPROVED_BY: 'approved_by',
    APPROVED_AT: 'approved_at',
    MESSAGE: 'message',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  ALBUMS: {
    ID: 'id',
    USER_ID: 'user_id',
    TITLE: 'title',
    DESCRIPTION: 'description',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  BUDGET_ITEMS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    TITLE: 'title',
    AMOUNT: 'amount',
    CURRENCY: 'currency',
    CATEGORY: 'category',
    PAID_BY: 'paid_by',
    DATE: 'date',
    SOURCE: 'source',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  COLLABORATIVE_NOTES: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    TITLE: 'title',
    CONTENT: 'content',
    CREATED_BY: 'created_by',
    IS_PINNED: 'is_pinned',
    LAST_EDITED_BY: 'last_edited_by',
    LAST_EDITED_AT: 'last_edited_at',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  COLLABORATIVE_SESSIONS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    DOCUMENT_TYPE: 'document_type',
    DOCUMENT_ID: 'document_id',
    CONTENT: 'content',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  CONTENT_CUSTOMIZATIONS: {
    ID: 'id',
    ITEM_ID: 'item_id',
    USER_ID: 'user_id',
    CUSTOMIZATION_TYPE: 'customization_type',
    ORIGINAL_VALUE: 'original_value',
    CUSTOMIZED_VALUE: 'customized_value',
    IS_PRIVATE: 'is_private',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    METADATA: 'metadata',
  },
  CONTENT_QUALITY_METRICS: {
    ID: 'id',
    ITEM_ID: 'item_id',
    TRIP_ID: 'trip_id',
    QUALITY_SCORE: 'quality_score',
    ENGAGEMENT_SCORE: 'engagement_score',
    POPULARITY_SCORE: 'popularity_score',
    USAGE_COUNT: 'usage_count',
    LAST_USED_AT: 'last_used_at',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    METADATA: 'metadata',
  },
  CONTENT_SHARING_HISTORY: {
    ID: 'id',
    ITEM_ID: 'item_id',
    SOURCE_TRIP_ID: 'source_trip_id',
    TARGET_TRIP_ID: 'target_trip_id',
    SHARED_BY: 'shared_by',
    SHARED_AT: 'shared_at',
    CUSTOMIZATIONS: 'customizations',
    METADATA: 'metadata',
  },
  CONTENT_SLUGS: {
    ID: 'id',
    CONTENT_TYPE: 'content_type',
    CONTENT_ID: 'content_id',
    SLUG: 'slug',
    IS_CANONICAL: 'is_canonical',
    CREATED_AT: 'created_at',
    CREATED_BY: 'created_by',
  },
  DESTINATION_TAGS: {
    ID: 'id',
    DESTINATION_ID: 'destination_id',
    TAG_ID: 'tag_id',
    ADDED_BY: 'added_by',
    CREATED_AT: 'created_at',
    CONFIDENCE_SCORE: 'confidence_score',
    VOTES_UP: 'votes_up',
    VOTES_DOWN: 'votes_down',
    IS_VERIFIED: 'is_verified',
  },
  DESTINATIONS: {
    ID: 'id',
    CREATED_AT: 'created_at',
    CITY: 'city',
    STATE_PROVINCE: 'state_province',
    COUNTRY: 'country',
    POPULARITY: 'popularity',
    LGBTQ_FRIENDLINESS: 'lgbtq_friendliness',
    ACCESSIBILITY: 'accessibility',
    CONTINENT: 'continent',
    BEST_SEASON: 'best_season',
    AVG_COST_PER_DAY: 'avg_cost_per_day',
    LOCAL_LANGUAGE: 'local_language',
    TIME_ZONE: 'time_zone',
    CUISINE_RATING: 'cuisine_rating',
    CULTURAL_ATTRACTIONS: 'cultural_attractions',
    NIGHTLIFE_RATING: 'nightlife_rating',
    FAMILY_FRIENDLY: 'family_friendly',
    OUTDOOR_ACTIVITIES: 'outdoor_activities',
    BEACH_QUALITY: 'beach_quality',
    SHOPPING_RATING: 'shopping_rating',
    SAFETY_RATING: 'safety_rating',
    WIFI_CONNECTIVITY: 'wifi_connectivity',
    PUBLIC_TRANSPORTATION: 'public_transportation',
    ECO_FRIENDLY_OPTIONS: 'eco_friendly_options',
    WALKABILITY: 'walkability',
    INSTAGRAM_WORTHY_SPOTS: 'instagram_worthy_spots',
    OFF_PEAK_APPEAL: 'off_peak_appeal',
    DIGITAL_NOMAD_FRIENDLY: 'digital_nomad_friendly',
    NAME: 'name',
    DESCRIPTION: 'description',
    IMAGE_URL: 'image_url',
    UPDATED_AT: 'updated_at',
    EMOJI: 'emoji',
    VISA_REQUIRED: 'visa_required',
    IMAGE_METADATA: 'image_metadata',
    BYLINE: 'byline',
    HIGHLIGHTS: 'highlights',
    PERFECT_FOR: 'perfect_for',
    LIKES_COUNT: 'likes_count',
    LATITUDE: 'latitude',
    LONGITUDE: 'longitude',
    AVG_DAYS: 'avg_days',
    ADDRESS: 'address',
    MAPBOX_ID: 'mapbox_id',
  },
  EXPENSES: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    TITLE: 'title',
    AMOUNT: 'amount',
    CATEGORY: 'category',
    DATE: 'date',
    PAID_BY: 'paid_by',
    CREATED_AT: 'created_at',
    CURRENCY: 'currency',
    SOURCE: 'source',
    UPDATED_AT: 'updated_at',
  },
  FOCUS_SESSIONS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    INITIATED_BY: 'initiated_by',
    SECTION_ID: 'section_id',
    SECTION_PATH: 'section_path',
    SECTION_NAME: 'section_name',
    ACTIVE: 'active',
    MESSAGE: 'message',
    CREATED_AT: 'created_at',
    EXPIRES_AT: 'expires_at',
  },
  IMAGE_METADATA: {
    ID: 'id',
    ENTITY_ID: 'entity_id',
    ENTITY_TYPE: 'entity_type',
    URL: 'url',
    ALT_TEXT: 'alt_text',
    ATTRIBUTION: 'attribution',
    PHOTOGRAPHER_NAME: 'photographer_name',
    PHOTOGRAPHER_URL: 'photographer_url',
    LICENSE: 'license',
    SOURCE: 'source',
    SOURCE_ID: 'source_id',
    WIDTH: 'width',
    HEIGHT: 'height',
    FOCAL_POINT_X: 'focal_point_x',
    FOCAL_POINT_Y: 'focal_point_y',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    ATTRIBUTION_HTML: 'attribution_html',
  },
  INVITATIONS: {
    ID: 'id',
    CREATED_AT: 'created_at',
    INVITED_BY: 'invited_by',
    TRIP_ID: 'trip_id',
    INVITATION_STATUS: 'invitation_status',
    EMAIL: 'email',
    TOKEN: 'token',
    EXPIRES_AT: 'expires_at',
  },
  ITEM_POPULARITY_METRICS: {
    ID: 'id',
    ITEM_ID: 'item_id',
    VIEWS_LAST_24H: 'views_last_24h',
    VIEWS_LAST_7D: 'views_last_7d',
    VIEWS_LAST_30D: 'views_last_30d',
    SHARES_LAST_24H: 'shares_last_24h',
    SHARES_LAST_7D: 'shares_last_7d',
    SHARES_LAST_30D: 'shares_last_30d',
    LIKES_LAST_24H: 'likes_last_24h',
    LIKES_LAST_7D: 'likes_last_7d',
    LIKES_LAST_30D: 'likes_last_30d',
    TRENDING_SCORE: 'trending_score',
    LAST_UPDATED: 'last_updated',
  },
  ITINERARY_ITEM_VOTES: {
    ID: 'id',
    ITINERARY_ITEM_ID: 'itinerary_item_id',
    USER_ID: 'user_id',
    VOTE_TYPE: 'vote_type',
    CREATED_AT: 'created_at',
  },
  ITINERARY_ITEMS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    TITLE: 'title',
    TYPE: 'type',
    DATE: 'date',
    START_TIME: 'start_time',
    END_TIME: 'end_time',
    LOCATION: 'location',
    PLACE_ID: 'place_id',
    LATITUDE: 'latitude',
    LONGITUDE: 'longitude',
    COST: 'cost',
    NOTES: 'notes',
    CREATED_AT: 'created_at',
    CREATED_BY: 'created_by',
    ITEM_TYPE: 'item_type',
    IS_CUSTOM: 'is_custom',
    DAY_NUMBER: 'day_number',
    ADDRESS: 'address',
    CATEGORY: 'category',
    STATUS: 'status',
    POSITION: 'position',
    ESTIMATED_COST: 'estimated_cost',
    CURRENCY: 'currency',
    DURATION_MINUTES: 'duration_minutes',
    SECTION_ID: 'section_id',
    UPDATED_AT: 'updated_at',
    COVER_IMAGE_URL: 'cover_image_url',
    CONTENT_LAYER: 'content_layer',
    ORIGINAL_ID: 'original_id',
    SOURCE_TRIP_ID: 'source_trip_id',
    ATTRIBUTION_TYPE: 'attribution_type',
    ATTRIBUTION_METADATA: 'attribution_metadata',
    SEO_TITLE: 'seo_title',
    SEO_DESCRIPTION: 'seo_description',
    CANONICAL_URL: 'canonical_url',
    SLUG: 'slug',
    META_KEYWORDS: 'meta_keywords',
    STRUCTURED_DATA: 'structured_data',
    SHARE_STATUS: 'share_status',
    SHARE_COUNT: 'share_count',
    LIKE_COUNT: 'like_count',
    VIEW_COUNT: 'view_count',
    VOTES: 'votes',
    LAST_MODIFIED_BY: 'last_modified_by',
    IS_FAVORITE: 'is_favorite',
    DAY: 'day',
  },
  ITINERARY_SECTIONS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    DAY_NUMBER: 'day_number',
    DATE: 'date',
    TITLE: 'title',
    POSITION: 'position',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  ITINERARY_TEMPLATE_ITEMS: {
    ID: 'id',
    TEMPLATE_ID: 'template_id',
    DAY: 'day',
    ITEM_ORDER: 'item_order',
    TITLE: 'title',
    DESCRIPTION: 'description',
    START_TIME: 'start_time',
    END_TIME: 'end_time',
    LOCATION: 'location',
    PLACE_ID: 'place_id',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  ITINERARY_TEMPLATE_SECTIONS: {
    ID: 'id',
    CREATED_AT: 'created_at',
  },
  ITINERARY_TEMPLATES: {
    ID: 'id',
    TITLE: 'title',
    SLUG: 'slug',
    DESCRIPTION: 'description',
    DESTINATION_ID: 'destination_id',
    DURATION_DAYS: 'duration_days',
    CATEGORY: 'category',
    CREATED_BY: 'created_by',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    IS_PUBLISHED: 'is_published',
    VIEW_COUNT: 'view_count',
    USE_COUNT: 'use_count',
    LIKE_COUNT: 'like_count',
    FEATURED: 'featured',
    COVER_IMAGE_URL: 'cover_image_url',
    GROUPSIZE: 'groupsize',
    TAGS: 'tags',
    TEMPLATE_TYPE: 'template_type',
    SOURCE_TRIP_ID: 'source_trip_id',
    VERSION: 'version',
    COPIED_COUNT: 'copied_count',
    LAST_COPIED_AT: 'last_copied_at',
    METADATA: 'metadata',
  },
  LIKES: {
    ID: 'id',
    USER_ID: 'user_id',
    ITEM_ID: 'item_id',
    ITEM_TYPE: 'item_type',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  LOCATIONS: {
    ID: 'id',
    NAME: 'name',
    PARENT_ID: 'parent_id',
    TYPE: 'type',
    CREATED_AT: 'created_at',
  },
  NOTE_TAGS: {
    NOTE_ID: 'note_id',
    TAG_ID: 'tag_id',
    ASSIGNED_AT: 'assigned_at',
  },
  NOTIFICATION_PREFERENCES: {
    ID: 'id',
    USER_ID: 'user_id',
    EMAIL_ENABLED: 'email_enabled',
    PUSH_ENABLED: 'push_enabled',
    IN_APP_ENABLED: 'in_app_enabled',
    TRIP_UPDATES: 'trip_updates',
    ITINERARY_CHANGES: 'itinerary_changes',
    MEMBER_ACTIVITY: 'member_activity',
    COMMENTS: 'comments',
    VOTES: 'votes',
    FOCUS_EVENTS: 'focus_events',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  NOTIFICATIONS: {
    ID: 'id',
    USER_ID: 'user_id',
    TRIP_ID: 'trip_id',
    SENDER_ID: 'sender_id',
    TITLE: 'title',
    CONTENT: 'content',
    NOTIFICATION_TYPE: 'notification_type',
    PRIORITY: 'priority',
    READ: 'read',
    ACTION_URL: 'action_url',
    REFERENCE_ID: 'reference_id',
    REFERENCE_TYPE: 'reference_type',
    CREATED_AT: 'created_at',
    EXPIRES_AT: 'expires_at',
  },
  PERMISSION_REQUESTS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    USER_ID: 'user_id',
    STATUS: 'status',
    MESSAGE: 'message',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  PLACES: {
    ID: 'id',
    NAME: 'name',
    DESCRIPTION: 'description',
    CATEGORY: 'category',
    ADDRESS: 'address',
    LATITUDE: 'latitude',
    LONGITUDE: 'longitude',
    DESTINATION_ID: 'destination_id',
    PRICE_LEVEL: 'price_level',
    RATING: 'rating',
    RATING_COUNT: 'rating_count',
    IMAGES: 'images',
    TAGS: 'tags',
    OPENING_HOURS: 'opening_hours',
    IS_VERIFIED: 'is_verified',
    SUGGESTED_BY: 'suggested_by',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    SOURCE: 'source',
    SOURCE_ID: 'source_id',
  },
  PREFERENCE_WEIGHTS: {
    ID: 'id',
    CATEGORY: 'category',
    SUBCATEGORY: 'subcategory',
    WEIGHT: 'weight',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  PROFILES: {
    ID: 'id',
    UPDATED_AT: 'updated_at',
    NAME: 'name',
    AVATAR_URL: 'avatar_url',
    IS_ADMIN: 'is_admin',
    EMAIL: 'email',
    USERNAME: 'username',
    COVER_IMAGE_URL: 'cover_image_url',
    BIO: 'bio',
    LOCATION: 'location',
    WEBSITE: 'website',
    IS_VERIFIED: 'is_verified',
    HOME_LOCATION_ID: 'home_location_id',
    FIRST_NAME: 'first_name',
    TRAVEL_PERSONALITY: 'travel_personality',
    TRAVEL_SQUAD: 'travel_squad',
    ONBOARDING_COMPLETED: 'onboarding_completed',
    ONBOARDING_COMPLETED_AT: 'onboarding_completed_at',
    ONBOARDING_STEP: 'onboarding_step',
  },
  QUESTIONS: {
    ID: 'id',
    FORM_ID: 'form_id',
    TITLE: 'title',
    DESCRIPTION: 'description',
    PLACEHOLDER: 'placeholder',
    IS_REQUIRED: 'is_required',
    QUESTION_TYPE: 'question_type',
    POSITION: 'position',
    OPTIONS: 'options',
    VALIDATION_RULES: 'validation_rules',
    CONDITIONAL_LOGIC: 'conditional_logic',
    DEFAULT_VALUE: 'default_value',
    MAX_CHARACTER_COUNT: 'max_character_count',
    SHOW_CHARACTER_COUNT: 'show_character_count',
    RATING_SCALE: 'rating_scale',
    RATING_TYPE: 'rating_type',
    ALLOWED_FILE_TYPES: 'allowed_file_types',
    MAX_FILE_SIZE: 'max_file_size',
    MAX_FILES: 'max_files',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  QUESTION_BRANCHING: {
    ID: 'id',
    FORM_ID: 'form_id',
    SOURCE_QUESTION_ID: 'source_question_id',
    TARGET_QUESTION_ID: 'target_question_id',
    CONDITION_TYPE: 'condition_type',
    CONDITION_VALUE: 'condition_value',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  REFERRALS: {
    ID: 'id',
    REFERRER_ID: 'referrer_id',
    REFERRED_ID: 'referred_id',
    REFERRAL_CODE: 'referral_code',
    TRIP_ID: 'trip_id',
    CONVERTED: 'converted',
    CREATED_AT: 'created_at',
    CONVERTED_AT: 'converted_at',
  },
  TAGS: {
    ID: 'id',
    NAME: 'name',
    SLUG: 'slug',
    CATEGORY: 'category',
    EMOJI: 'emoji',
    DESCRIPTION: 'description',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    CREATED_BY: 'created_by',
    IS_VERIFIED: 'is_verified',
    USE_COUNT: 'use_count',
    METADATA: 'metadata',
  },
  TEMPLATE_APPLICATIONS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    TEMPLATE_ID: 'template_id',
    APPLIED_AT: 'applied_at',
    APPLIED_BY: 'applied_by',
    VERSION_USED: 'version_used',
    SUCCESS_RATE: 'success_rate',
    OPTIMIZATION_LEVEL: 'optimization_level',
    FALLBACKS_USED: 'fallbacks_used',
    APPLICATION_METADATA: 'application_metadata',
  },
  TRIP_COMMENT_LIKES: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    COMMENT_ID: 'comment_id',
    USER_ID: 'user_id',
    CREATED_AT: 'created_at',
  },
  TRIP_HISTORY: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    CREATED_AT: 'created_at',
    USER_ID: 'user_id',
    ACTION_TYPE: 'action_type',
    DETAILS: 'details',
  },
  TRIP_IMAGES: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    FILE_PATH: 'file_path',
    FILE_NAME: 'file_name',
    CONTENT_TYPE: 'content_type',
    SIZE_BYTES: 'size_bytes',
    CREATED_BY: 'created_by',
    CREATED_AT: 'created_at',
    WIDTH: 'width',
    HEIGHT: 'height',
    DESCRIPTION: 'description',
    ALBUM_ID: 'album_id',
  },
  TRIP_ITEM_COMMENTS: {
    ID: 'id',
    ITEM_ID: 'item_id',
    TRIP_ID: 'trip_id',
    USER_ID: 'user_id',
    CONTENT: 'content',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  TRIP_MEMBERS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    USER_ID: 'user_id',
    ROLE: 'role',
    JOINED_AT: 'joined_at',
    INVITED_BY: 'invited_by',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  TRIP_NOTES: {
    TRIP_ID: 'trip_id',
    CONTENT: 'content',
    UPDATED_BY: 'updated_by',
    UPDATED_AT: 'updated_at',
    USER_ID: 'user_id',
    ALBUM_ID: 'album_id',
    ID: 'id',
    TITLE: 'title',
  },
  TRIP_TAGS: {
    TRIP_ID: 'trip_id',
    TAG_ID: 'tag_id',
    ASSIGNED_AT: 'assigned_at',
  },
  TRIP_TEMPLATE_USES: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    TEMPLATE_ID: 'template_id',
    APPLIED_AT: 'applied_at',
    APPLIED_BY: 'applied_by',
    VERSION_USED: 'version_used',
    MODIFICATIONS: 'modifications',
  },
  TRIP_VOTE_OPTIONS: {
    ID: 'id',
    POLL_ID: 'poll_id',
    TITLE: 'title',
    DESCRIPTION: 'description',
    IMAGE_URL: 'image_url',
    CREATED_AT: 'created_at',
  },
  TRIP_VOTE_POLLS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    TITLE: 'title',
    DESCRIPTION: 'description',
    IS_ACTIVE: 'is_active',
    CREATED_BY: 'created_by',
    EXPIRES_AT: 'expires_at',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  TRIP_VOTES: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    POLL_ID: 'poll_id',
    OPTION_ID: 'option_id',
    USER_ID: 'user_id',
    CREATED_AT: 'created_at',
  },
  TRIPS: {
    ID: 'id',
    TITLE: 'title',
    DESCRIPTION: 'description',
    START_DATE: 'start_date',
    END_DATE: 'end_date',
    CREATED_BY: 'created_by',
    IS_PUBLIC: 'is_public',
    PRIVACY_SETTING: 'privacy_setting',
    LOCATION: 'location',
    TRIP_TYPE: 'trip_type',
    STATUS: 'status',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  USER_ACTIVITY_HISTORY: {
    ID: 'id',
    USER_ID: 'user_id',
    ITEM_ID: 'item_id',
    INTERACTION_TYPE: 'interaction_type',
    INTERACTION_DATA: 'interaction_data',
    CREATED_AT: 'created_at',
    METADATA: 'metadata',
  },
  USER_INTERACTIONS: {
    ID: 'id',
    USER_ID: 'user_id',
    DESTINATION_ID: 'destination_id',
    INTERACTION_TYPE: 'interaction_type',
    CREATED_AT: 'created_at',
  },
  USER_INTERESTS: {
    ID: 'id',
    USER_ID: 'user_id',
    TAG_ID: 'tag_id',
    STRENGTH: 'strength',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  USER_LOGIN_HISTORY: {
    ID: 'id',
    USER_ID: 'user_id',
    LOGIN_AT: 'login_at',
    IP_ADDRESS: 'ip_address',
    USER_AGENT: 'user_agent',
    SUCCESS: 'success',
    METHOD: 'method',
    CREATED_AT: 'created_at',
  },
  USER_PREFERENCES: {
    ID: 'id',
    USER_ID: 'user_id',
    TRAVEL_STYLES: 'travel_styles',
    PREFERRED_PACE: 'preferred_pace',
    BUDGET_RANGE: 'budget_range',
    PREFERRED_ACTIVITY_TYPES: 'preferred_activity_types',
    PREFERRED_TIMES_OF_DAY: 'preferred_times_of_day',
    ACCESSIBILITY_NEEDS: 'accessibility_needs',
    DIETARY_RESTRICTIONS: 'dietary_restrictions',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
    METADATA: 'metadata',
  },
  USER_PRESENCE: {
    ID: 'id',
    USER_ID: 'user_id',
    TRIP_ID: 'trip_id',
    DOCUMENT_ID: 'document_id',
    STATUS: 'status',
    LAST_ACTIVE: 'last_active',
  },
  USER_SUGGESTED_TAGS: {
    ID: 'id',
    USER_ID: 'user_id',
    DESTINATION_ID: 'destination_id',
    NAME: 'name',
    SLUG: 'slug',
    CATEGORY: 'category',
    STATUS: 'status',
    ADMIN_NOTES: 'admin_notes',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  USER_TRAVEL: {
    USER_ID: 'user_id',
    DESTINATION_ID: 'destination_id',
    VISITED_AT: 'visited_at',
  },
  USERS: {
    ID: 'id',
    EMAIL: 'email',
    NAME: 'name',
    AVATAR_URL: 'avatar_url',
    CREATED_AT: 'created_at',
    IS_ADMIN: 'is_admin',
    BIO: 'bio',
    LOCATION: 'location',
    INTERESTS: 'interests',
    UPDATED_AT: 'updated_at',
    USERNAME: 'username',
    FULL_NAME: 'full_name',
    LAST_SIGN_IN_AT: 'last_sign_in_at',
  },
  VALIDATION_LOGS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    TEMPLATE_ID: 'template_id',
    IS_VALID: 'is_valid',
    VALIDATION_ERRORS: 'validation_errors',
    VALIDATED_AT: 'validated_at',
    VALIDATED_BY: 'validated_by',
  },
  VOTES: {
    ID: 'id',
    ITINERARY_ITEM_ID: 'itinerary_item_id',
    USER_ID: 'user_id',
    VOTE_TYPE: 'vote_type',
    CREATED_AT: 'created_at',
  },
  TEMPLATE_TAGS: {
    ID: 'id',
    TEMPLATE_ID: 'template_id',
    TAG_ID: 'tag_id',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  TRIP_SETTINGS: {
    ID: 'id',
    TRIP_ID: 'trip_id',
    SETTING_TYPE: 'setting_type',
    VALUE: 'value',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  TEAM_INVITATIONS: {
    ID: 'id',
    TEAM_ID: 'team_id',
    INVITED_BY: 'invited_by',
    INVITATION_STATUS: 'invitation_status',
    EMAIL: 'email',
    TOKEN: 'token',
    EXPIRES_AT: 'expires_at',
  },
  TEAM_MEMBERS: {
    ID: 'id',
    TEAM_ID: 'team_id',
    USER_ID: 'user_id',
    ROLE: 'role',
    CREATED_AT: 'created_at',
    INVITED_BY: 'invited_by',
    JOINED_AT: 'joined_at',
  },
  TEAMS: {
    ID: 'id',
    NAME: 'name',
    DESCRIPTION: 'description',
    CREATED_AT: 'created_at',
    UPDATED_AT: 'updated_at',
  },
  ITINERARY_ITEM_REACTIONS: {
    ID: 'id',
    ITINERARY_ITEM_ID: 'itinerary_item_id',
    USER_ID: 'user_id',
    EMOJI: 'emoji',
    CREATED_AT: 'created_at',
  },
} as const;

export const ENUMS = {
  TRIP_ROLES: {
    ADMIN: 'admin',
    EDITOR: 'editor',
    CONTRIBUTOR: 'contributor',
    VIEWER: 'viewer',
  },
  ITEM_STATUS: {
    SUGGESTED: 'suggested',
    CONFIRMED: 'confirmed',
    REJECTED: 'rejected',
  },
  TRIP_STATUS: {
    PLANNING: 'planning',
    UPCOMING: 'upcoming',
    IN_PROGRESS: 'in_progress',
    COMPLETED: 'completed',
    CANCELLED: 'cancelled',
  },
  PERMISSION_STATUS: {
    PENDING: 'pending',
    APPROVED: 'approved',
    DENIED: 'denied',
  },
  IMAGE_TYPE: {
    DESTINATION: 'destination',
    TRIP_COVER: 'trip_cover',
    USER_AVATAR: 'user_avatar',
    TEMPLATE_COVER: 'template_cover',
  },
  CONTENT_TYPE: {
    TRIP: 'trip',
    ITINERARY_ITEM: 'itinerary_item',
    DESTINATION: 'destination',
    COLLECTION: 'collection',
    TEMPLATE: 'template',
  },
  QUESTION_TYPE: {
    TEXT: 'text',
    SELECT: 'select',
    MULTI_SELECT: 'multi_select',
    DATE: 'date',
    NUMBER: 'number',
    BOOLEAN: 'boolean',
  },
  FORM_STATUS: {
    DRAFT: 'draft',
    PUBLISHED: 'published',
    ARCHIVED: 'archived',
  },
  FORM_VISIBILITY: {
    PUBLIC: 'public',
    PRIVATE: 'private',
    SHARED: 'shared',
  },
  ITINERARY_CATEGORY: {
    ICONIC_LANDMARKS: 'Iconic Landmarks',
    LOCAL_SECRETS: 'Local Secrets',
    CULTURAL_EXPERIENCES: 'Cultural Experiences',
    OUTDOOR_ADVENTURES: 'Outdoor Adventures',
    FOOD_AND_DRINK: 'Food & Drink',
    NIGHTLIFE: 'Nightlife',
    RELAXATION: 'Relaxation',
    SHOPPING: 'Shopping',
    GROUP_ACTIVITIES: 'Group Activities',
    DAY_EXCURSIONS: 'Day Excursions',
    ACCOMMODATIONS: 'Accommodations',
    TRANSPORTATION: 'Transportation',
    FLEXIBLE_OPTIONS: 'Flexible Options',
    SPECIAL_OCCASIONS: 'Special Occasions',
    OTHER: 'Other',
  },
  ITINERARY_ITEM_STATUS: {
    PENDING: 'pending',
    APPROVED: 'approved',
    REJECTED: 'rejected',
  },
  INVITATION_STATUS: {
    PENDING: 'pending',
    ACCEPTED: 'accepted',
    DECLINED: 'declined',
    EXPIRED: 'expired',
  },
  PRIVACY_SETTING: {
    PRIVATE: 'private',
    SHARED_WITH_LINK: 'shared_with_link',
    PUBLIC: 'public',
  },
  TRIP_PRIVACY_SETTING: {
    PRIVATE: 'private',
    SHARED_WITH_LINK: 'shared_with_link',
    PUBLIC: 'public',
  },
  PLACE_CATEGORY: {
    ATTRACTION: 'attraction',
    RESTAURANT: 'restaurant',
    CAFE: 'cafe',
    HOTEL: 'hotel',
    LANDMARK: 'landmark',
    SHOPPING: 'shopping',
    TRANSPORT: 'transport',
    OTHER: 'other',
  },
  TAG_STATUS: {
    PENDING: 'pending',
    APPROVED: 'approved',
    REJECTED: 'rejected',
  },
  TRAVEL_PACE: {
    VERY_SLOW: 'very_slow',
    SLOW: 'slow',
    MODERATE: 'moderate',
    FAST: 'fast',
    VERY_FAST: 'very_fast',
  },
  TRAVEL_PERSONALITY_TYPE: {
    PLANNER: 'planner',
    ADVENTURER: 'adventurer',
    FOODIE: 'foodie',
    SIGHTSEER: 'sightseer',
    RELAXER: 'relaxer',
    CULTURE: 'culture',
  },
  TRAVEL_SQUAD_TYPE: {
    FRIENDS: 'friends',
    FAMILY: 'family',
    PARTNER: 'partner',
    SOLO: 'solo',
    COWORKERS: 'coworkers',
    MIXED: 'mixed',
  },
  TRAVEL_STYLE: {
    ADVENTUROUS: 'adventurous',
    RELAXED: 'relaxed',
    CULTURAL: 'cultural',
    LUXURY: 'luxury',
    BUDGET: 'budget',
    FAMILY: 'family',
    SOLO: 'solo',
    NIGHTLIFE: 'nightlife',
    NATURE: 'nature',
    FOOD_FOCUSED: 'food_focused',
  },
  BUDGET_CATEGORY: {
    ACCOMMODATION: 'accommodation',
    TRANSPORTATION: 'transportation',
    FOOD: 'food',
    ACTIVITIES: 'activities',
    SHOPPING: 'shopping',
    OTHER: 'other',
  },
  TRIP_TYPE: {
    LEISURE: 'leisure',
    BUSINESS: 'business',
    FAMILY: 'family',
    SOLO: 'solo',
    GROUP: 'group',
    OTHER: 'other',
  },
  VOTE_TYPE: {
    UP: 'up',
    DOWN: 'down',
  },
  INTERACTION_TYPE: {
    LIKE: 'like',
    VISIT: 'visit',
    BOOKMARK: 'bookmark',
    TAG: 'tag',
  },
  URL_FORMAT: {
    CANONICAL: 'canonical',
    SHORT: 'short',
    SOCIAL: 'social',
    TRACKING: 'tracking',
  },
  TRIP_ACTION_TYPE: {
    TRIP_CREATED: 'TRIP_CREATED',
    TRIP_UPDATED: 'TRIP_UPDATED',
    ITINERARY_ITEM_ADDED: 'ITINERARY_ITEM_ADDED',
    ITINERARY_ITEM_UPDATED: 'ITINERARY_ITEM_UPDATED',
    ITINERARY_ITEM_DELETED: 'ITINERARY_ITEM_DELETED',
    MEMBER_ADDED: 'MEMBER_ADDED',
    MEMBER_REMOVED: 'MEMBER_REMOVED',
    MEMBER_ROLE_UPDATED: 'MEMBER_ROLE_UPDATED',
    INVITATION_SENT: 'INVITATION_SENT',
    ACCESS_REQUEST_SENT: 'ACCESS_REQUEST_SENT',
    ACCESS_REQUEST_UPDATED: 'ACCESS_REQUEST_UPDATED',
    NOTE_CREATED: 'NOTE_CREATED',
    NOTE_UPDATED: 'NOTE_UPDATED',
    NOTE_DELETED: 'NOTE_DELETED',
    IMAGE_UPLOADED: 'IMAGE_UPLOADED',
    TAG_ADDED: 'TAG_ADDED',
    TAG_REMOVED: 'TAG_REMOVED',
    SPLITWISE_GROUP_LINKED: 'SPLITWISE_GROUP_LINKED',
    SPLITWISE_GROUP_UNLINKED: 'SPLITWISE_GROUP_UNLINKED',
    SPLITWISE_GROUP_CREATED_AND_LINKED: 'SPLITWISE_GROUP_CREATED_AND_LINKED',
    COMMENT_ADDED: 'COMMENT_ADDED',
    COMMENT_UPDATED: 'COMMENT_UPDATED',
    COMMENT_DELETED: 'COMMENT_DELETED',
    VOTE_CAST: 'VOTE_CAST',
    FOCUS_INITIATED: 'FOCUS_INITIATED',
  },
} as const;

// Foreign Key Relationships
export const RELATIONSHIPS = {
  ACCESS_REQUESTS: [
    { column: 'approved_by', referencesTable: 'users', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
    { column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  ALBUMS: [{ column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' }],
  COLLABORATIVE_NOTES: [
    { column: 'created_by', referencesTable: 'profiles', referencesColumn: 'id' },
    { column: 'last_edited_by', referencesTable: 'profiles', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
  ],
  COLLABORATIVE_SESSIONS: [{ column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' }],
  FORM_COLLABORATORS: [
    { column: 'form_id', referencesTable: 'forms', referencesColumn: 'id' },
    { column: 'invited_by', referencesTable: 'users', referencesColumn: 'id' },
    { column: 'user_id', referencesTable: 'users', referencesColumn: 'id' },
  ],
  FORMS: [{ column: 'created_by', referencesTable: 'users', referencesColumn: 'id' }],
  INTERACTIONS: [{ column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' }],
  ITINERARY_ITEM_VOTES: [
    { column: 'itinerary_item_id', referencesTable: 'itinerary_items', referencesColumn: 'id' },
    { column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  ITINERARY_ITEMS: [
    { column: 'place_id', referencesTable: 'places', referencesColumn: 'id' },
    { column: 'section_id', referencesTable: 'itinerary_sections', referencesColumn: 'id' },
    { column: 'suggested_by', referencesTable: 'profiles', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
  ],
  ITINERARY_SECTIONS: [{ column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' }],
  ITINERARY_TEMPLATE_ITEMS: [
    { column: 'place_id', referencesTable: 'places', referencesColumn: 'id' },
    { column: 'template_id', referencesTable: 'itinerary_templates', referencesColumn: 'id' },
  ],
  ITINERARY_TEMPLATE_SECTIONS: [
    { column: 'template_id', referencesTable: 'itinerary_templates', referencesColumn: 'id' },
  ],
  ITINERARY_TEMPLATES: [
    { column: 'created_by', referencesTable: 'users', referencesColumn: 'id' },
    { column: 'destination_id', referencesTable: 'destinations', referencesColumn: 'id' },
    { column: 'source_trip_id', referencesTable: 'trips', referencesColumn: 'id' },
  ],
  ITEM_POPULARITY_METRICS: [
    { column: 'item_id', referencesTable: 'itinerary_items', referencesColumn: 'id' },
  ],
  LIKES: [{ column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' }],
  LOCATIONS: [{ column: 'parent_id', referencesTable: 'locations', referencesColumn: 'id' }],
  NOTE_TAGS: [
    { column: 'note_id', referencesTable: 'trip_notes', referencesColumn: 'id' },
    { column: 'tag_id', referencesTable: 'tags', referencesColumn: 'id' },
  ],
  NOTIFICATION_PREFERENCES: [
    { column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  NOTIFICATIONS: [
    { column: 'recipient_id', referencesTable: 'profiles', referencesColumn: 'id' },
    { column: 'sender_id', referencesTable: 'profiles', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
  ],
  PERMISSION_REQUESTS: [
    { column: 'requestor_id', referencesTable: 'profiles', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
  ],
  PLACES: [
    { column: 'destination_id', referencesTable: 'destinations', referencesColumn: 'id' },
    { column: 'suggested_by', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  PREFERENCE_WEIGHTS: [
    { column: 'preference_id', referencesTable: 'user_preferences', referencesColumn: 'id' },
    { column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  PROFILES: [{ column: 'id', referencesTable: 'auth.users', referencesColumn: 'id' }],
  QUESTION_BRANCHING: [
    { column: 'question_id', referencesTable: 'questions', referencesColumn: 'id' },
    { column: 'target_question_id', referencesTable: 'questions', referencesColumn: 'id' },
  ],
  QUESTIONS: [{ column: 'form_id', referencesTable: 'forms', referencesColumn: 'id' }],
  REFERRALS: [
    { column: 'referrer_id', referencesTable: 'profiles', referencesColumn: 'id' },
    { column: 'referred_id', referencesTable: 'profiles', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
  ],
  RESPONSES: [
    { column: 'question_id', referencesTable: 'questions', referencesColumn: 'id' },
    { column: 'session_id', referencesTable: 'response_sessions', referencesColumn: 'id' },
  ],
  RESPONSE_SESSIONS: [
    { column: 'form_id', referencesTable: 'forms', referencesColumn: 'id' },
    { column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  SURVEY_RESPONSES: [
    { column: 'question_id', referencesTable: 'questions', referencesColumn: 'id' },
    { column: 'session_id', referencesTable: 'response_sessions', referencesColumn: 'id' },
  ],
  TEMPLATE_APPLICATIONS: [
    { column: 'template_id', referencesTable: 'itinerary_templates', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
  ],
  TEMPLATE_TAGS: [
    { column: 'tag_id', referencesTable: 'tags', referencesColumn: 'id' },
    { column: 'template_id', referencesTable: 'itinerary_templates', referencesColumn: 'id' },
  ],
  TEAM_INVITATIONS: [
    { column: 'invited_by', referencesTable: 'users', referencesColumn: 'id' },
    { column: 'team_id', referencesTable: 'teams', referencesColumn: 'id' },
  ],
  TEAM_MEMBERS: [
    { column: 'invited_by', referencesTable: 'users', referencesColumn: 'id' },
    { column: 'team_id', referencesTable: 'teams', referencesColumn: 'id' },
    { column: 'user_id', referencesTable: 'users', referencesColumn: 'id' },
  ],
  TRIP_COMMENT_LIKES: [
    { column: 'comment_id', referencesTable: 'trip_item_comments', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
    { column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  TRIP_ITEM_COMMENTS: [
    { column: 'item_id', referencesTable: 'itinerary_items', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
    { column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  TRIP_ITEM_VOTES: [
    { column: 'itinerary_item_id', referencesTable: 'itinerary_items', referencesColumn: 'id' },
    { column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  TRIP_MEMBERS: [
    { column: 'invited_by', referencesTable: 'users', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
    { column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  TRIP_NOTES: [
    { column: 'album_id', referencesTable: 'albums', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
    { column: 'updated_by', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  TRIP_SETTINGS: [{ column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' }],
  TRIP_TAGS: [
    { column: 'tag_id', referencesTable: 'tags', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
  ],
  TRIP_TEMPLATE_USES: [
    { column: 'template_id', referencesTable: 'itinerary_templates', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
  ],
  TRIP_VOTE_OPTIONS: [
    { column: 'poll_id', referencesTable: 'trip_vote_polls', referencesColumn: 'id' },
  ],
  TRIP_VOTE_POLLS: [
    { column: 'created_by', referencesTable: 'profiles', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
  ],
  TRIP_VOTES: [
    { column: 'option_id', referencesTable: 'trip_vote_options', referencesColumn: 'id' },
    { column: 'poll_id', referencesTable: 'trip_vote_polls', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
    { column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  TRIPS: [
    { column: 'created_by', referencesTable: 'profiles', referencesColumn: 'id' },
    { column: 'destination_id', referencesTable: 'destinations', referencesColumn: 'id' },
    { column: 'updated_by', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  USER_ACTIVITY_HISTORY: [
    { column: 'item_id', referencesTable: 'itinerary_items', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
    { column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  USER_INTERACTIONS: [{ column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' }],
  USER_INTERESTS: [
    { column: 'tag_id', referencesTable: 'tags', referencesColumn: 'id' },
    { column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  USER_LOGIN_HISTORY: [{ column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' }],
  USER_PREFERENCES: [{ column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' }],
  USER_PRESENCE: [
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
    { column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  USER_SUGGESTED_TAGS: [
    { column: 'tag_id', referencesTable: 'tags', referencesColumn: 'id' },
    { column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  USER_TRAVEL: [
    { column: 'destination_id', referencesTable: 'destinations', referencesColumn: 'id' },
    { column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' },
  ],
  VALIDATION_LOGS: [
    { column: 'template_id', referencesTable: 'itinerary_templates', referencesColumn: 'id' },
    { column: 'trip_id', referencesTable: 'trips', referencesColumn: 'id' },
  ],
  VOTES: [{ column: 'user_id', referencesTable: 'profiles', referencesColumn: 'id' }],
} as const;

// Export type definitions for enum values to ensure type safety
export type TripRole = (typeof ENUMS.TRIP_ROLES)[keyof typeof ENUMS.TRIP_ROLES];
export type ItemStatus = (typeof ENUMS.ITEM_STATUS)[keyof typeof ENUMS.ITEM_STATUS];
export type TripStatus = (typeof ENUMS.TRIP_STATUS)[keyof typeof ENUMS.TRIP_STATUS];
export type PermissionStatus =
  (typeof ENUMS.PERMISSION_STATUS)[keyof typeof ENUMS.PERMISSION_STATUS];
export type ImageType = (typeof ENUMS.IMAGE_TYPE)[keyof typeof ENUMS.IMAGE_TYPE];
export type ContentType = (typeof ENUMS.CONTENT_TYPE)[keyof typeof ENUMS.CONTENT_TYPE];
export type QuestionType = (typeof ENUMS.QUESTION_TYPE)[keyof typeof ENUMS.QUESTION_TYPE];
export type FormStatus = (typeof ENUMS.FORM_STATUS)[keyof typeof ENUMS.FORM_STATUS];
export type FormVisibility = (typeof ENUMS.FORM_VISIBILITY)[keyof typeof ENUMS.FORM_VISIBILITY];
export type ItineraryCategory =
  (typeof ENUMS.ITINERARY_CATEGORY)[keyof typeof ENUMS.ITINERARY_CATEGORY];
export type ItineraryItemStatus = (typeof ENUMS.ITINERARY_ITEM_STATUS)[keyof typeof ENUMS.ITINERARY_ITEM_STATUS];
export type InvitationStatus = (typeof ENUMS.INVITATION_STATUS)[keyof typeof ENUMS.INVITATION_STATUS];
export type PrivacySetting = (typeof ENUMS.PRIVACY_SETTING)[keyof typeof ENUMS.PRIVACY_SETTING];
export type TripPrivacySetting = (typeof ENUMS.TRIP_PRIVACY_SETTING)[keyof typeof ENUMS.TRIP_PRIVACY_SETTING];
export type PlaceCategory = (typeof ENUMS.PLACE_CATEGORY)[keyof typeof ENUMS.PLACE_CATEGORY];
export type TagStatus = (typeof ENUMS.TAG_STATUS)[keyof typeof ENUMS.TAG_STATUS];
export type TravelPace = (typeof ENUMS.TRAVEL_PACE)[keyof typeof ENUMS.TRAVEL_PACE];
export type TravelPersonalityType = (typeof ENUMS.TRAVEL_PERSONALITY_TYPE)[keyof typeof ENUMS.TRAVEL_PERSONALITY_TYPE];
export type TravelSquadType = (typeof ENUMS.TRAVEL_SQUAD_TYPE)[keyof typeof ENUMS.TRAVEL_SQUAD_TYPE];
export type TravelStyle = (typeof ENUMS.TRAVEL_STYLE)[keyof typeof ENUMS.TRAVEL_STYLE];
export type BudgetCategory = (typeof ENUMS.BUDGET_CATEGORY)[keyof typeof ENUMS.BUDGET_CATEGORY];
export type TripType = (typeof ENUMS.TRIP_TYPE)[keyof typeof ENUMS.TRIP_TYPE];
export type VoteType = (typeof ENUMS.VOTE_TYPE)[keyof typeof ENUMS.VOTE_TYPE];
export type InteractionType = (typeof ENUMS.INTERACTION_TYPE)[keyof typeof ENUMS.INTERACTION_TYPE];
export type UrlFormat = (typeof ENUMS.URL_FORMAT)[keyof typeof ENUMS.URL_FORMAT];
export type TripActionType = (typeof ENUMS.TRIP_ACTION_TYPE)[keyof typeof ENUMS.TRIP_ACTION_TYPE];

// Table-related type definitions
export type TableNames = (typeof TABLES)[keyof typeof TABLES];
export type TableFields<T extends keyof typeof FIELDS> =
  (typeof FIELDS)[T][keyof (typeof FIELDS)[T]];

// Legacy exports for backward compatibility (deprecated, use direct exports instead)
export const DB_TABLES = TABLES;
export const DB_FIELDS = FIELDS;
export const DB_ENUMS = ENUMS;
export const DB_RELATIONSHIPS = RELATIONSHIPS;
